// PR Sprint 7.25 Phase 10 — anonymous landing brand-bible preview.
//
// POST /api/landing/preview-bible
//
// Public, unauthenticated endpoint that powers the landing's
// "$ helm read <url>" demo. Takes a URL, scrapes the public surface
// (lib/brand-bible/web-scraper), runs the existing Opus brand-bible
// builder (lib/brand-bible/auto-generate), and returns the
// AutoGeneratedBrandBible shape WITHOUT persisting it. The landing
// renders the bible inline so a stranger sees their own brand
// reflected back before being asked to sign up.
//
// Cost protection (anonymous endpoint!):
//   - IP-keyed rate limit: 3 calls per hour per IP.
//   - Cheap-out short-circuit: scrape fail → 422 with a friendly
//     hint, no Opus call fired.
//   - We DO NOT persist anything server-side. The bible only lives
//     in the landing's component state; the signup flow re-builds
//     after auth using the URL the visitor types (already wired via
//     `helm:pendingBrandUrl` sessionStorage from /signup).

import { NextResponse } from 'next/server';
import { scrapeWebsite } from '@/lib/brand-bible/web-scraper';
import {
  generateBrandBibleFromSources,
  type SourceForGeneration,
} from '@/lib/brand-bible/auto-generate';
import { checkRateLimit } from '@/lib/rate-limit';

// Opus runs 20-40s on full bibles; allow 75s ceiling on this
// serverless function so Vercel doesn't kill us mid-call.
export const maxDuration = 90;

function clientIp(req: Request): string {
  // Prefer the leftmost x-forwarded-for entry (Vercel's edge passes
  // the originating client IP there). Fall back to a header literal
  // so an unproxied dev request still gets a stable key.
  const xff = req.headers.get('x-forwarded-for');
  if (xff) return xff.split(',')[0]!.trim();
  const real = req.headers.get('x-real-ip');
  if (real) return real.trim();
  return 'unknown';
}

function normaliseUrl(raw: string): string | null {
  const trimmed = raw.trim();
  if (!trimmed) return null;
  const withScheme = /^https?:\/\//i.test(trimmed)
    ? trimmed
    : `https://${trimmed}`;
  try {
    const u = new URL(withScheme);
    if (u.protocol !== 'http:' && u.protocol !== 'https:') return null;
    if (!u.hostname.includes('.')) return null;
    return u.toString();
  } catch {
    return null;
  }
}

function brandNameFromUrl(url: string): string {
  try {
    const host = new URL(url).hostname.replace(/^www\./, '');
    // First label before the TLD as a starter project name.
    const root = host.split('.')[0] ?? host;
    return root.charAt(0).toUpperCase() + root.slice(1);
  } catch {
    return 'Your brand';
  }
}

export async function POST(request: Request) {
  try {
    const ip = clientIp(request);
    // 3 calls / IP / hour is plenty for honest demos. Bots that try
    // a higher rate just see 429s; the loader on the landing surfaces
    // the rate-limit error message back to the user.
    const limit = checkRateLimit(`landing-preview:${ip}`, 3, 60 * 60 * 1000);
    if (!limit.allowed) {
      const mins = Math.ceil(limit.resetMs / 60_000);
      return NextResponse.json(
        {
          ok: false,
          error: 'Too many previews from this network',
          hint: `Try again in ${mins} minute${mins === 1 ? '' : 's'}, or sign up to keep generating.`,
        },
        { status: 429 },
      );
    }

    const body = await request.json().catch(() => ({}));
    const rawUrl = typeof body.url === 'string' ? body.url : '';
    const url = normaliseUrl(rawUrl);
    if (!url) {
      return NextResponse.json(
        {
          ok: false,
          error: 'Enter a valid URL (yourbrand.com)',
        },
        { status: 400 },
      );
    }

    const scrape = await scrapeWebsite(url);
    if (scrape.error) {
      return NextResponse.json(
        {
          ok: false,
          error: 'Could not read that URL',
          hint:
            scrape.error.length > 0
              ? scrape.error
              : 'The site may be blocking bots or be temporarily down.',
        },
        { status: 422 },
      );
    }
    // Sanity check — if the scraper got nothing back, an Opus call
    // would hallucinate. Bail with a helpful message instead.
    const evidenceLength =
      (scrape.title?.length ?? 0) +
      (scrape.metaDescription?.length ?? 0) +
      (scrape.bodyText?.length ?? 0) +
      scrape.headlines.length * 20;
    if (evidenceLength < 80) {
      return NextResponse.json(
        {
          ok: false,
          error: 'Not enough public content on that page',
          hint: 'Try a homepage URL (helm-style sites tend to be SPA empty shells without text — try a marketing page).',
        },
        { status: 422 },
      );
    }

    const sources: SourceForGeneration[] = [
      { type: 'website', data: scrape },
    ];
    const brandName = brandNameFromUrl(url);
    const bible = await generateBrandBibleFromSources(sources, brandName);

    return NextResponse.json({
      ok: true,
      bible,
      brandName,
      url,
    });
  } catch (e) {
    // Most realistic failure modes: Anthropic 5xx, JSON parse on
    // model output, scrape timeout. All surface as a single
    // "try again" so the founder doesn't drop into a stack trace.
    console.error('[landing/preview-bible] failed:', e);
    return NextResponse.json(
      {
        ok: false,
        error: 'Helm could not finish reading that brand',
        hint: 'Try again in a moment, or sign up and we will retry on our side.',
      },
      { status: 500 },
    );
  }
}
