// PR #26 — Sprint 3: Auto-Generate Brand Bible.
//
// POST /api/brand-bible/auto-generate
//
// Reads every analyzed source for the project and asks Opus to
// derive a brand bible draft. Returns the AutoGeneratedBrandBible
// shape — apply-generated is what writes the result back into
// projects.brand_context.
//
// Body: { projectId }
// Returns: { success, brandBible, sourcesCount }
import { createClient } from '@/lib/supabase/server';
import { db } from '@/lib/db';
import { brandBibleSources, projects } from '@/lib/db/schema';
import { eq, and } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import {
  generateBrandBibleFromSources,
  type SourceForGeneration,
} from '@/lib/brand-bible/auto-generate';

// Opus at 4096 tokens typically returns in 20-40s; allow headroom.
export const maxDuration = 90;

export async function POST(request: Request) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const body = await request.json().catch(() => ({}));
  const { projectId } = body as { projectId?: string };
  if (!projectId) {
    return NextResponse.json(
      { error: 'projectId required' },
      { status: 400 }
    );
  }

  const [project] = await db
    .select()
    .from(projects)
    .where(and(eq(projects.id, projectId), eq(projects.userId, user.id)))
    .limit(1);
  if (!project) {
    return NextResponse.json({ error: 'Project not found' }, { status: 404 });
  }

  const analyzedSources = await db
    .select()
    .from(brandBibleSources)
    .where(
      and(
        eq(brandBibleSources.projectId, projectId),
        eq(brandBibleSources.userId, user.id),
        eq(brandBibleSources.status, 'analyzed')
      )
    );

  if (analyzedSources.length === 0) {
    return NextResponse.json(
      {
        error:
          'No analyzed sources yet. Add a website source and click Analyze first.',
      },
      { status: 400 }
    );
  }

  const sources: SourceForGeneration[] = analyzedSources.map((s) => ({
    type: s.sourceType,
    data: s.analysisResult,
  }));

  try {
    const brandBible = await generateBrandBibleFromSources(
      sources,
      project.name
    );
    return NextResponse.json({
      success: true,
      brandBible,
      sourcesCount: analyzedSources.length,
    });
  } catch (e) {
    const message = e instanceof Error ? e.message : 'Generation failed';
    return NextResponse.json(
      { success: false, error: message },
      { status: 500 }
    );
  }
}
