"""
visual_consolidated.py
======================

Single-file consolidation of the 6 visual modules for review purposes.

In production, keep these split into separate files:
  - visual_schema.py              Pydantic models for VisualPromptIR + 5 blocks
  - platform_visual_language.py   Per-platform visual conventions + helpers
  - visual_subject_extractor.py   Mini-LLM call: pain_point + caption -> SubjectBlock
  - visual_prompt_builder.py      Composes the IR from inputs (incl. archetype defaults + dynamic negatives)
  - visual_renderer_flux.py       Renders IR -> Flux/fal.ai prompt string
  - visual_validator.py           Soft validation rules

This consolidated file is the same code, organized into sections, for end-to-end
review without jumping between files.

Architecture
------------
  PAIN_POINT + CAPTION + BRAND_BIBLE
        |
        v
  build_visual_prompt_ir() ---> mini-LLM call ---> SubjectBlock
        |                       (visual_subject_extractor)
        |
        v
  VisualPromptIR (5 blocks: Subject + Style + Brand + Platform + Negative)
        |
        v
  validate_visual_prompt_ir()  ---> [list of failures]
        |
        v
  render_for_flux(ir, boost_subject=False)  ---> flux_prompt_string -> fal.ai

Sections:
  1. Schema                  enums (incl. VisualStrategy), blocks, IR aggregate
  2. Platform Visual Lang    per-platform visual conventions + helpers
  3. Subject Extractor       mini-LLM call for SubjectBlock
  4. Prompt Builder          composes IR; archetype defaults; dynamic negatives; cache_key
  5. Renderer (Flux)         IR -> Flux/fal.ai string; optional boost_subject flag
  6. Validator               soft validation rules

Changes vs v1.0:
  - VisualStrategy enum (HUMAN_STORY, METAPHOR_DRIVEN, PRODUCT_SHOT, etc.)
  - SubjectBlock.emotional_anchor (single short tag for filtering/learning)
  - SubjectBlock.visual_strategy (output of extractor, drives validation)
  - Stronger SUBJECT_EXTRACTION_PROMPT (emotional consequence + thumb-stopper framing)
  - STYLE_DEFAULTS_BY_ARCHETYPE (13 archetypes with camera/lighting/DOF defaults)
  - Dynamic NegativeBlock (DEFAULT + per-platform + per-style overlays)
  - cache_key field in VisualPromptMetadata (for v1.5 cache layer)
  - boost_subject optional flag in render_for_flux (experimental, off by default)
  - emotional_anchor coherence check in validator
  - Pydantic model_validator: visual_metaphor required when visual_strategy=METAPHOR_DRIVEN

Dependencies:
  - pydantic >= 2.0

Version: 2.0 (MVP Phase 1)
"""

from __future__ import annotations

import hashlib
import json
import time
from enum import Enum
from typing import Any, Protocol

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


# ============================================================================
# SECTION 1: SCHEMA (originally visual_schema.py)
# ============================================================================


class StyleType(str, Enum):
    PHOTOGRAPHY = "photography"
    ILLUSTRATION = "illustration"
    SCREENSHOT = "screenshot"
    MIXED_MEDIA = "mixed_media"
    ABSTRACT = "abstract"
    THREE_D_RENDER = "3d_render"


class CameraType(str, Enum):
    CLOSE_UP = "close-up"
    MEDIUM_SHOT = "medium shot"
    WIDE_SHOT = "wide shot"
    OVERHEAD = "overhead shot"
    DUTCH_ANGLE = "dutch angle"
    MACRO = "macro lens"
    PORTRAIT_85MM = "85mm portrait lens"
    DOCUMENTARY = "documentary handheld"
    FLAT_LAY = "flat lay top-down"


class LightingType(str, Enum):
    NATURAL_SOFT = "natural soft light"
    GOLDEN_HOUR = "golden hour warm light"
    STUDIO = "studio lighting with key + fill"
    HARSH_SHADOWS = "harsh dramatic shadows"
    NEON = "neon glow accent"
    OVERHEAD_FLAT = "flat overhead lighting"
    LOW_KEY = "low-key moody lighting"
    BACKLIT = "backlit silhouette"
    WINDOW_LIGHT = "soft window light"


class AspectRatio(str, Enum):
    SQUARE = "1:1"
    PORTRAIT_4_5 = "4:5"
    PORTRAIT_9_16 = "9:16"
    LANDSCAPE_16_9 = "16:9"
    LANDSCAPE_3_2 = "3:2"


class DepthOfField(str, Enum):
    SHALLOW = "shallow depth of field with bokeh background"
    MEDIUM = "medium depth of field"
    DEEP = "deep focus, everything sharp"


class VisualStrategy(str, Enum):
    """High-level approach the visual takes. Output by the subject extractor."""
    HUMAN_STORY = "human_story"
    METAPHOR_DRIVEN = "metaphor_driven"
    PRODUCT_SHOT = "product_shot"
    DATA_VISUALIZATION = "data_visualization"
    BEHIND_SCENES = "behind_scenes"
    BRAND_HERITAGE = "brand_heritage"


class SubjectBlock(BaseModel):
    """What is IN the image. Generated by mini-LLM call."""
    model_config = ConfigDict(extra="forbid")

    main_subject: str = Field(..., min_length=15, max_length=300)
    composition: str = Field(..., min_length=5, max_length=150)
    setting: str = Field(..., min_length=5, max_length=200)
    mood_descriptor: str = Field(..., min_length=3, max_length=80)
    emotional_anchor: str | None = Field(default=None, max_length=30,
                                         description="Single dominant emotion as a short tag.")
    visual_strategy: VisualStrategy
    visual_metaphor: str | None = Field(default=None, max_length=200,
                                        description="Required when visual_strategy is METAPHOR_DRIVEN.")

    @field_validator("main_subject")
    @classmethod
    def no_text_instructions(cls, v: str) -> str:
        bad_terms = ("with text", "with caption", "text overlay", "text saying",
                     "watermark", "logo overlay")
        v_lower = v.lower()
        for term in bad_terms:
            if term in v_lower:
                raise ValueError(
                    f"main_subject contains text-instruction phrase '{term}'. "
                    f"Text overlays are added separately in post-production. "
                    f"Describe only the visual subject."
                )
        return v

    @model_validator(mode="after")
    def metaphor_required_for_metaphor_driven(self) -> "SubjectBlock":
        if self.visual_strategy == VisualStrategy.METAPHOR_DRIVEN and not self.visual_metaphor:
            raise ValueError(
                "visual_metaphor is required when visual_strategy is METAPHOR_DRIVEN. "
                "Either set a metaphor or pick a different visual_strategy."
            )
        return self


class StyleBlock(BaseModel):
    model_config = ConfigDict(extra="forbid")

    style_type: StyleType
    camera: CameraType | None = None
    lighting: LightingType | None = None
    depth_of_field: DepthOfField | None = None
    additional_style_notes: str | None = Field(default=None, max_length=200)


class BrandBlock(BaseModel):
    model_config = ConfigDict(extra="forbid")

    archetype: str = Field(..., min_length=2, max_length=50)
    mood: str = Field(..., min_length=3, max_length=100)
    color_palette: list[str] = Field(default_factory=list, max_length=5)
    voice_descriptor: str | None = Field(default=None, max_length=100)


class PlatformBlock(BaseModel):
    model_config = ConfigDict(extra="forbid")

    platform: str
    content_type: str
    aspect_ratio: AspectRatio
    visual_language_notes: str = Field(..., min_length=10, max_length=400)


DEFAULT_NEGATIVE_TERMS: list[str] = [
    "text in image",
    "watermark",
    "logo overlay",
    "oversaturated colors",
    "plastic-looking skin",
    "distorted hands or faces",
    "extra fingers",
    "AI illustration aesthetic",
    "generic stock imagery",
    "amateur lighting",
    "blurry low quality",
    "cropped subject",
]


class NegativeBlock(BaseModel):
    model_config = ConfigDict(extra="forbid")

    avoid_terms: list[str] = Field(default_factory=lambda: list(DEFAULT_NEGATIVE_TERMS),
                                   min_length=1, max_length=30)


class VisualPromptMetadata(BaseModel):
    model_config = ConfigDict(extra="forbid")

    pain_point_excerpt: str = Field(..., max_length=300)
    caption_excerpt: str = Field(..., max_length=300)
    target_platform: str
    target_content_type: str
    subject_extractor_model: str | None = None
    subject_extractor_latency_ms: int | None = None
    cache_key: str | None = Field(default=None,
                                  description="Stable hash for v1.5 SubjectBlock cache layer.")


class VisualPromptIR(BaseModel):
    """Renderer-agnostic intermediate representation of a visual prompt."""
    model_config = ConfigDict(extra="forbid")

    subject: SubjectBlock
    style: StyleBlock
    brand: BrandBlock
    platform: PlatformBlock
    negative: NegativeBlock = Field(default_factory=NegativeBlock)
    metadata: VisualPromptMetadata


# ============================================================================
# SECTION 2: PLATFORM VISUAL LANGUAGE (originally platform_visual_language.py)
# ============================================================================


PLATFORM_VISUAL_LANGUAGE: dict[str, dict[str, dict]] = {

    "instagram": {
        "photo": {
            "aspect_ratio": AspectRatio.PORTRAIT_4_5,
            "visual_register": "lifestyle, aspirational, mobile-first",
            "composition_notes": "subject centered or rule-of-thirds, ample negative space, designed to thumbstop in feed",
            "color_treatment": "vibrant but natural saturation, slight warm bias, consistent with mobile screen rendering",
        },
        "carousel": {
            "aspect_ratio": AspectRatio.SQUARE,
            "visual_register": "editorial, clean, slide-as-standalone",
            "composition_notes": "simple compositions that read at thumbnail size, subject filling 50-70% of frame, clean negative space for any future text overlay",
            "color_treatment": "consistent palette across all slides, muted-to-mid saturation, high readability",
        },
        "ugc": {
            "aspect_ratio": AspectRatio.PORTRAIT_9_16,
            "visual_register": "bold, high-contrast, attention-stopper",
            "composition_notes": "subject centered or upper-third, room for text overlay at top and bottom thirds, face-forward when subject is human",
            "color_treatment": "saturated, contrasty, optimized for tiny thumbnail visibility",
        },
    },

    "linkedin": {
        "photo": {
            "aspect_ratio": AspectRatio.PORTRAIT_4_5,
            "visual_register": "clean editorial, business context, professional but human",
            "composition_notes": "subject centered, neutral or office-adjacent setting, documentary feel over staged",
            "color_treatment": "muted palette, low-to-mid saturation, blue-gray cool bias is acceptable, avoid neon",
        },
        "carousel": {
            "aspect_ratio": AspectRatio.SQUARE,
            "visual_register": "document-style, headline + supporting visual, white-paper feel",
            "composition_notes": "high contrast subject vs background, asymmetric composition that leaves room for prominent headline text overlay, flat-lay or clean studio shots work well",
            "color_treatment": "muted, professional, single accent color, avoid lifestyle warmth or aspirational glow",
        },
        "ugc": {
            "aspect_ratio": AspectRatio.PORTRAIT_9_16,
            "visual_register": "professional but candid, talking-head friendly",
            "composition_notes": "subject upper-center, eye level, neutral background, looking slightly off-camera or direct",
            "color_treatment": "natural skin tones, soft window-style lighting",
        },
    },

    "x": {
        "photo": {
            "aspect_ratio": AspectRatio.LANDSCAPE_16_9,
            "visual_register": "documentary, raw, screenshot-friendly",
            "composition_notes": "wider framing, subject can be off-center, scene matters as much as subject, less polished",
            "color_treatment": "natural / unprocessed feel, accept some grain or imperfection",
        },
        "ugc": {
            "aspect_ratio": AspectRatio.PORTRAIT_9_16,
            "visual_register": "raw, in-the-moment, unpolished",
            "composition_notes": "subject filling frame, handheld feel acceptable, low production value works",
            "color_treatment": "natural, no filters, slight underexposure OK",
        },
    },

    "threads": {
        "photo": {
            "aspect_ratio": AspectRatio.SQUARE,
            "visual_register": "casual, in-progress, less polished than Instagram",
            "composition_notes": "subject centered, simple, looks like a phone snap rather than a photoshoot",
            "color_treatment": "natural, slightly under-saturated, no heavy editing",
        },
        "ugc": {
            "aspect_ratio": AspectRatio.PORTRAIT_9_16,
            "visual_register": "raw, conversational, talking-friend energy",
            "composition_notes": "subject close to camera, casual framing, eye contact",
            "color_treatment": "natural skin tones, ambient lighting only",
        },
    },

    "facebook": {
        "photo": {
            "aspect_ratio": AspectRatio.SQUARE,
            "visual_register": "warm, community-oriented, less edgy",
            "composition_notes": "subject centered, narrative composition, often shows people or relatable scenes",
            "color_treatment": "warm tones, mid saturation, accessible to older audiences",
        },
        "carousel": {
            "aspect_ratio": AspectRatio.SQUARE,
            "visual_register": "story-driven, sequential narrative",
            "composition_notes": "consistent visual language across slides, subject can vary but treatment stays uniform",
            "color_treatment": "consistent warm palette across slides",
        },
        "ugc": {
            "aspect_ratio": AspectRatio.PORTRAIT_9_16,
            "visual_register": "warm, community-friendly, talking-head with context",
            "composition_notes": "subject centered, may show a setting that signals community",
            "color_treatment": "warm natural tones",
        },
    },

    "tiktok": {
        "ugc": {
            "aspect_ratio": AspectRatio.PORTRAIT_9_16,
            "visual_register": "bold, high-contrast, attention-stopper for thumbnail",
            "composition_notes": "subject centered or upper-third, expressive face if human, room for text overlay across top, designed to win the 0.5-second swipe test as a static frame",
            "color_treatment": "high saturation, high contrast, optimized for thumbnail visibility at 80px",
        },
    },
}


ASPECT_RATIO_BY_PLATFORM_AND_TYPE: dict[tuple[str, str], AspectRatio] = {
    (platform, content_type): spec["aspect_ratio"]
    for platform, content_types in PLATFORM_VISUAL_LANGUAGE.items()
    for content_type, spec in content_types.items()
}


def get_visual_language(platform: str, content_type: str) -> dict:
    platform = platform.lower()
    content_type = content_type.lower()
    if platform not in PLATFORM_VISUAL_LANGUAGE:
        raise ValueError(
            f"Platform '{platform}' has no visual language defined. "
            f"Supported: {sorted(PLATFORM_VISUAL_LANGUAGE.keys())}"
        )
    if content_type not in PLATFORM_VISUAL_LANGUAGE[platform]:
        raise ValueError(
            f"Content type '{content_type}' not supported for visuals on "
            f"platform '{platform}'. Supported: "
            f"{sorted(PLATFORM_VISUAL_LANGUAGE[platform].keys())}"
        )
    return PLATFORM_VISUAL_LANGUAGE[platform][content_type]


def get_aspect_ratio(platform: str, content_type: str) -> AspectRatio:
    return get_visual_language(platform, content_type)["aspect_ratio"]


def format_visual_language_notes(spec: dict) -> str:
    return (
        f"Visual register: {spec['visual_register']}. "
        f"Composition: {spec['composition_notes']}. "
        f"Color treatment: {spec['color_treatment']}."
    )


# ============================================================================
# SECTION 3: SUBJECT EXTRACTOR (originally visual_subject_extractor.py)
# ============================================================================


SUBJECT_EXTRACTION_PROMPT = """You are a senior visual director specialized in founder and SaaS marketing content. Your job is to translate a marketing post into a powerful, specific visual scene that an image generator (Flux, Midjourney, etc.) can render into a thumb-stopper.

INPUTS:

PAIN_POINT (what the post is fundamentally about, the audience pain or insight):
{pain_point}

CAPTION (what the person says about the image; NOT what the image should literally show):
{caption}

BRAND ARCHETYPE: {brand_archetype}
BRAND MOOD: {brand_mood}

YOUR TASK:

Output a JSON object describing the visual subject. The image should evoke the EMOTIONAL HUMAN CONSEQUENCE of the pain point, not the tool or the literal caption. For B2B/SaaS pain points, the strongest images show the human moment that the pain creates, not a screenshot or an abstract concept.

OUTPUT SCHEMA (return ONLY this JSON, no commentary):

{{
  "main_subject": "<concrete description of the central subject. 15-300 chars. E.g., 'A solo founder hunched over a laptop at 2am, 8 browser tabs glowing on the screen'>",
  "composition": "<framing and arrangement. 5-150 chars. E.g., 'centered, slight low angle, subject filling 60% of frame'>",
  "setting": "<environment/context. 5-200 chars. E.g., 'messy home office, warm desk lamp, late night, papers scattered'>",
  "mood_descriptor": "<emotional tone as a full phrase, 3-80 chars. E.g., 'exhausted but determined', 'quietly confident', 'frustrated and overwhelmed'>",
  "emotional_anchor": "<single dominant emotion as a short tag, 1-3 words max, 30 chars. E.g., 'exhaustion', 'determination', 'relief', 'frustration'. Or null if no single dominant emotion stands out.>",
  "visual_strategy": "<one of: human_story, metaphor_driven, product_shot, data_visualization, behind_scenes, brand_heritage>",
  "visual_metaphor": "<required if visual_strategy is 'metaphor_driven', 3-200 chars. Otherwise null.>"
}}

VISUAL STRATEGY GUIDE (pick exactly one):
- human_story: Subject is a person in a real moment. DEFAULT for SaaS/founder pain points.
- metaphor_driven: Subject is a concrete object/scene representing an abstract concept. Use when human story doesn't fit.
- product_shot: Subject is a product or interface. Use sparingly, only for product launches.
- data_visualization: Subject is a chart, graph, or screenshot. Use only when the data IS the story.
- behind_scenes: Subject is a workspace, process, or in-progress moment.
- brand_heritage: Subject is brand-anchored imagery (founder portrait, signature setting). Use rarely.

CRITICAL RULES:
- The image MUST work as a standalone thumb-stopper. Would a stranger scrolling at 2am stop on this image?
- Focus on the EMOTIONAL HUMAN CONSEQUENCE of the pain point, not the tool itself.
- Do NOT describe text overlays, captions, watermarks, UI elements, or logos. Those are added separately in post-production.
- Do NOT just paraphrase the caption. Translate it to visuals.
- For pain points about software/tools, prefer showing the human consequence (a tired founder) over the tool itself (a screenshot).
- The mood_descriptor and emotional_anchor should align with the BRAND_MOOD. If brand mood is "warm and human" don't pick "cold and clinical".
- emotional_anchor is a short tag (1-3 words). mood_descriptor is the full phrase. They describe the same emotion at two different levels of detail.
- Keep the visual concept achievable for an image model. Avoid impossible spatial relationships, hyperspecific cultural references, or anything requiring legible text.

Return only the JSON. No preamble, no markdown fences, no thinking."""


class LLMClient(Protocol):
    """Minimal protocol the extractor needs from an LLM client."""
    async def complete_json(self, *, model: str, prompt: str, max_tokens: int = 600) -> str:
        ...


async def extract_subject_block(
    *,
    pain_point: str,
    caption: str,
    brand_archetype: str,
    brand_mood: str,
    client: LLMClient,
    model: str = "claude-haiku-4-5",
    max_retries: int = 2,
) -> SubjectBlock:
    prompt = SUBJECT_EXTRACTION_PROMPT.format(
        pain_point=pain_point.strip(),
        caption=caption.strip(),
        brand_archetype=brand_archetype.strip(),
        brand_mood=brand_mood.strip(),
    )

    last_error: Exception | None = None

    for attempt in range(max_retries + 1):
        try:
            raw_response = await client.complete_json(
                model=model,
                prompt=prompt,
                max_tokens=600,
            )
            payload = _extract_json_object(raw_response)
            return SubjectBlock.model_validate(payload)
        except (json.JSONDecodeError, ValueError) as e:
            last_error = e
            continue

    raise SubjectExtractionError(
        f"Failed to extract SubjectBlock after {max_retries + 1} attempts. "
        f"Last error: {last_error}"
    )


def _extract_json_object(raw: str) -> dict[str, Any]:
    text = raw.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1] if "\n" in text else text
        if text.endswith("```"):
            text = text.rsplit("```", 1)[0]
        text = text.strip()
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1 or end < start:
        raise json.JSONDecodeError("No JSON object found in response", text, 0)
    return json.loads(text[start : end + 1])


class SubjectExtractionError(Exception):
    """Raised when the extractor fails after all retries."""


# ============================================================================
# SECTION 4: PROMPT BUILDER (originally visual_prompt_builder.py)
# ============================================================================


# Style defaults by brand archetype (overrides content_type defaults when matched)
STYLE_DEFAULTS_BY_ARCHETYPE: dict[str, dict] = {
    "rebel":     {"camera": CameraType.DUTCH_ANGLE,   "lighting": LightingType.HARSH_SHADOWS, "depth_of_field": DepthOfField.SHALLOW},
    "outlaw":    {"camera": CameraType.DUTCH_ANGLE,   "lighting": LightingType.LOW_KEY,       "depth_of_field": DepthOfField.SHALLOW},
    "sage":      {"camera": CameraType.MEDIUM_SHOT,   "lighting": LightingType.WINDOW_LIGHT,  "depth_of_field": DepthOfField.DEEP},
    "creator":   {"camera": CameraType.CLOSE_UP,      "lighting": LightingType.GOLDEN_HOUR,   "depth_of_field": DepthOfField.SHALLOW},
    "hero":      {"camera": CameraType.WIDE_SHOT,     "lighting": LightingType.BACKLIT,       "depth_of_field": DepthOfField.MEDIUM},
    "caregiver": {"camera": CameraType.CLOSE_UP,      "lighting": LightingType.NATURAL_SOFT,  "depth_of_field": DepthOfField.SHALLOW},
    "everyman":  {"camera": CameraType.DOCUMENTARY,   "lighting": LightingType.NATURAL_SOFT,  "depth_of_field": DepthOfField.MEDIUM},
    "ruler":     {"camera": CameraType.PORTRAIT_85MM, "lighting": LightingType.STUDIO,        "depth_of_field": DepthOfField.SHALLOW},
    "magician":  {"camera": CameraType.CLOSE_UP,      "lighting": LightingType.LOW_KEY,       "depth_of_field": DepthOfField.SHALLOW},
    "innocent":  {"camera": CameraType.MEDIUM_SHOT,   "lighting": LightingType.NATURAL_SOFT,  "depth_of_field": DepthOfField.MEDIUM},
    "explorer":  {"camera": CameraType.WIDE_SHOT,     "lighting": LightingType.GOLDEN_HOUR,   "depth_of_field": DepthOfField.DEEP},
    "lover":     {"camera": CameraType.CLOSE_UP,      "lighting": LightingType.GOLDEN_HOUR,   "depth_of_field": DepthOfField.SHALLOW},
    "jester":    {"camera": CameraType.MEDIUM_SHOT,   "lighting": LightingType.NATURAL_SOFT,  "depth_of_field": DepthOfField.MEDIUM},
}


# Dynamic negative terms by platform and style
NEGATIVE_BY_PLATFORM: dict[str, list[str]] = {
    "linkedin": ["neon colors", "casual lifestyle imagery", "selfie aesthetic"],
    "tiktok": ["muted desaturated palette", "static composition", "professional studio look"],
    "instagram": ["corporate stock photography", "boring composition"],
    "x": ["overly polished imagery", "studio lighting"],
    "threads": ["magazine-style production", "overly polished imagery"],
    "facebook": ["edgy harsh aesthetic", "low-key dark imagery"],
}

NEGATIVE_BY_STYLE: dict[StyleType, list[str]] = {
    StyleType.PHOTOGRAPHY: ["cartoonish illustration", "anime style", "flat 2D drawing"],
    StyleType.ILLUSTRATION: ["photorealistic 3D render", "uncanny valley faces"],
    StyleType.SCREENSHOT: ["artistic interpretation", "stylized rendering"],
    StyleType.MIXED_MEDIA: [],
    StyleType.ABSTRACT: ["literal subject", "documentary realism"],
    StyleType.THREE_D_RENDER: ["flat illustration", "2D drawing"],
}


def build_negative_terms(
    platform: str,
    style_type: StyleType,
    base: list[str] | None = None,
) -> list[str]:
    """Combine default negative terms with platform-specific and style-specific
    additions. Deduplicates while preserving order.
    """
    combined: list[str] = list(base) if base is not None else list(DEFAULT_NEGATIVE_TERMS)
    combined.extend(NEGATIVE_BY_PLATFORM.get(platform.lower(), []))
    combined.extend(NEGATIVE_BY_STYLE.get(style_type, []))

    seen: set[str] = set()
    deduped: list[str] = []
    for term in combined:
        term_lower = term.lower()
        if term_lower not in seen:
            seen.add(term_lower)
            deduped.append(term)
    return deduped


class BrandBibleVisualSlice:
    """Minimal contract for what the visual builder needs from BrandBible."""

    def __init__(
        self,
        archetype: str,
        photography_mood: str,
        image_style: str,
        colors: list[str] | None = None,
        voice_descriptor: str | None = None,
    ):
        self.archetype = archetype
        self.photography_mood = photography_mood
        self.image_style = image_style
        self.colors = colors or []
        self.voice_descriptor = voice_descriptor


async def build_visual_prompt_ir(
    *,
    pain_point: str,
    caption: str,
    brand_bible: BrandBibleVisualSlice,
    platform: str,
    content_type: str,
    llm_client: LLMClient,
    subject_extractor_model: str = "claude-haiku-4-5",
) -> VisualPromptIR:
    """Build a complete VisualPromptIR by composing all 5 blocks."""
    platform = platform.lower()
    content_type = content_type.lower()

    start_ms = int(time.monotonic() * 1000)
    subject = await extract_subject_block(
        pain_point=pain_point,
        caption=caption,
        brand_archetype=brand_bible.archetype,
        brand_mood=brand_bible.photography_mood,
        client=llm_client,
        model=subject_extractor_model,
    )
    extraction_latency_ms = int(time.monotonic() * 1000) - start_ms

    style = _build_style_block(brand_bible, content_type)

    brand = BrandBlock(
        archetype=brand_bible.archetype,
        mood=brand_bible.photography_mood,
        color_palette=brand_bible.colors,
        voice_descriptor=brand_bible.voice_descriptor,
    )

    visual_lang_spec = get_visual_language(platform, content_type)
    platform_block = PlatformBlock(
        platform=platform,
        content_type=content_type,
        aspect_ratio=visual_lang_spec["aspect_ratio"],
        visual_language_notes=format_visual_language_notes(visual_lang_spec),
    )

    negative = NegativeBlock(
        avoid_terms=build_negative_terms(platform, style.style_type)
    )

    cache_key = _generate_cache_key(
        pain_point=pain_point,
        caption=caption,
        brand_archetype=brand_bible.archetype,
        brand_mood=brand_bible.photography_mood,
        platform=platform,
        content_type=content_type,
    )
    metadata = VisualPromptMetadata(
        pain_point_excerpt=pain_point[:300],
        caption_excerpt=caption[:300],
        target_platform=platform,
        target_content_type=content_type,
        subject_extractor_model=subject_extractor_model,
        subject_extractor_latency_ms=extraction_latency_ms,
        cache_key=cache_key,
    )

    return VisualPromptIR(
        subject=subject,
        style=style,
        brand=brand,
        platform=platform_block,
        negative=negative,
        metadata=metadata,
    )


def _build_style_block(brand: BrandBibleVisualSlice, content_type: str) -> StyleBlock:
    """Lookup precedence: archetype defaults > content_type defaults."""
    try:
        style_type = StyleType(brand.image_style.lower())
    except ValueError:
        style_type = StyleType.PHOTOGRAPHY

    archetype_key = brand.archetype.lower().strip()
    archetype_defaults = STYLE_DEFAULTS_BY_ARCHETYPE.get(archetype_key)

    if archetype_defaults:
        defaults = archetype_defaults
    else:
        defaults_by_content_type = {
            "photo": {
                "camera": CameraType.MEDIUM_SHOT,
                "lighting": LightingType.NATURAL_SOFT,
                "depth_of_field": DepthOfField.SHALLOW,
            },
            "carousel": {
                "camera": CameraType.FLAT_LAY,
                "lighting": LightingType.STUDIO,
                "depth_of_field": DepthOfField.DEEP,
            },
            "ugc": {
                "camera": CameraType.MEDIUM_SHOT,
                "lighting": LightingType.WINDOW_LIGHT,
                "depth_of_field": DepthOfField.MEDIUM,
            },
        }
        defaults = defaults_by_content_type.get(content_type, defaults_by_content_type["photo"])

    return StyleBlock(
        style_type=style_type,
        camera=defaults["camera"],
        lighting=defaults["lighting"],
        depth_of_field=defaults["depth_of_field"],
        additional_style_notes=None,
    )


def _generate_cache_key(
    *,
    pain_point: str,
    caption: str,
    brand_archetype: str,
    brand_mood: str,
    platform: str,
    content_type: str,
) -> str:
    """Stable hash for caching SubjectBlock outputs (v1.5 cache layer)."""
    combined = "||".join([
        pain_point.strip(),
        caption.strip(),
        brand_archetype.strip().lower(),
        brand_mood.strip().lower(),
        platform.lower(),
        content_type.lower(),
    ])
    return hashlib.sha256(combined.encode("utf-8")).hexdigest()[:16]


# ============================================================================
# SECTION 5: RENDERER FLUX (originally visual_renderer_flux.py)
# ============================================================================


STYLE_LEAD: dict[StyleType, str] = {
    StyleType.PHOTOGRAPHY: "Professional photograph",
    StyleType.ILLUSTRATION: "Editorial illustration",
    StyleType.SCREENSHOT: "Realistic screen capture",
    StyleType.MIXED_MEDIA: "Mixed-media composition",
    StyleType.ABSTRACT: "Abstract visual composition",
    StyleType.THREE_D_RENDER: "Cinematic 3D render",
}


def render_for_flux(ir: VisualPromptIR, *, boost_subject: bool = False) -> str:
    """Convert a VisualPromptIR to a Flux/fal.ai prompt string.

    Args:
        ir:             the validated VisualPromptIR
        boost_subject:  EXPERIMENTAL. If True, wraps the main_subject in
                        weighted-attention syntax: (subject:1.3). Some Flux
                        variants (Pro, Dev) respect this; Schnell may not.
                        A/B test before promoting to default. Off by default.
    """
    parts: list[str] = []

    style_lead = STYLE_LEAD.get(ir.style.style_type, "Professional photograph")
    subject_text = ir.subject.main_subject
    if boost_subject:
        subject_text = f"({subject_text}:1.3)"
    parts.append(f"{style_lead} of {subject_text}")
    parts.append(f"in {ir.subject.setting}")
    parts.append(ir.subject.composition)
    parts.append(f"mood: {ir.subject.mood_descriptor}")

    if ir.subject.visual_metaphor:
        parts.append(f"visual metaphor: {ir.subject.visual_metaphor}")

    style_technicals: list[str] = []
    if ir.style.camera:
        style_technicals.append(f"shot with {ir.style.camera.value}")
    if ir.style.lighting:
        style_technicals.append(ir.style.lighting.value)
    if ir.style.depth_of_field:
        style_technicals.append(ir.style.depth_of_field.value)
    if ir.style.additional_style_notes:
        style_technicals.append(ir.style.additional_style_notes)
    if style_technicals:
        parts.append("style: " + ", ".join(style_technicals))

    brand_parts: list[str] = []
    brand_parts.append(f"{ir.brand.archetype} brand archetype")
    brand_parts.append(f"{ir.brand.mood} mood")
    if ir.brand.color_palette:
        brand_parts.append(f"color palette of {', '.join(ir.brand.color_palette)}")
    parts.append("brand: " + ", ".join(brand_parts))

    parts.append(ir.platform.visual_language_notes)
    parts.append(f"{_aspect_phrase(ir.platform.aspect_ratio)} aspect ratio")

    if ir.negative.avoid_terms:
        parts.append(f"avoid: {', '.join(ir.negative.avoid_terms)}")

    return ". ".join(parts) + "."


def render_negative_prompt(ir: VisualPromptIR) -> str:
    return ", ".join(ir.negative.avoid_terms)


def get_image_size_for_fal(aspect_ratio: AspectRatio) -> str:
    mapping: dict[AspectRatio, str] = {
        AspectRatio.SQUARE: "square_hd",
        AspectRatio.PORTRAIT_4_5: "portrait_4_3",
        AspectRatio.PORTRAIT_9_16: "portrait_16_9",
        AspectRatio.LANDSCAPE_16_9: "landscape_16_9",
        AspectRatio.LANDSCAPE_3_2: "landscape_4_3",
    }
    return mapping.get(aspect_ratio, "square_hd")


def _aspect_phrase(aspect: AspectRatio) -> str:
    descriptors = {
        AspectRatio.SQUARE: "square 1:1",
        AspectRatio.PORTRAIT_4_5: "portrait 4:5",
        AspectRatio.PORTRAIT_9_16: "tall vertical 9:16",
        AspectRatio.LANDSCAPE_16_9: "wide landscape 16:9",
        AspectRatio.LANDSCAPE_3_2: "landscape 3:2",
    }
    return descriptors.get(aspect, aspect.value)


# ============================================================================
# SECTION 6: VALIDATOR (originally visual_validator.py)
# ============================================================================


SUBJECT_LAZY_TERMS: tuple[str, ...] = (
    "concept of", "abstract representation",
    "generic image of", "stock photo of",
    "people doing", "person at a desk",
    "modern office", "diverse team", "happy customer",
)

SUBJECT_TEXT_TERMS: tuple[str, ...] = (
    "with text", "with caption", "text overlay", "logo",
    "watermark", "title card",
)

MOOD_CLUSTERS: dict[str, set[str]] = {
    "warm": {"warm", "human", "friendly", "cozy", "intimate", "natural"},
    "clinical": {"clinical", "minimal", "clean", "sterile", "precise", "technical"},
    "gritty": {"gritty", "raw", "documentary", "unfiltered", "moody", "dark"},
    "aspirational": {"aspirational", "polished", "luxe", "elegant", "refined"},
    "energetic": {"energetic", "bold", "vibrant", "dynamic", "high-energy"},
}


def validate_visual_prompt_ir(ir: VisualPromptIR) -> list[str]:
    failures: list[str] = []
    failures.extend(_check_subject_not_lazy(ir))
    failures.extend(_check_subject_no_text_instructions(ir))
    failures.extend(_check_brand_mood_coherence(ir))
    failures.extend(_check_color_palette_size(ir))
    failures.extend(_check_negative_block_completeness(ir))
    failures.extend(_check_aspect_ratio_consistency(ir))
    return failures


def _check_subject_not_lazy(ir: VisualPromptIR) -> list[str]:
    subject_lower = ir.subject.main_subject.lower()
    for term in SUBJECT_LAZY_TERMS:
        if term in subject_lower:
            return [
                f"SubjectBlock.main_subject contains lazy phrase '{term}'. "
                f"Re-run extract_subject_block with feedback that the visual "
                f"should be specific and concrete, not abstract or stock."
            ]
    return []


def _check_subject_no_text_instructions(ir: VisualPromptIR) -> list[str]:
    failures: list[str] = []
    fields_to_check = {
        "composition": ir.subject.composition,
        "setting": ir.subject.setting,
        "visual_metaphor": ir.subject.visual_metaphor or "",
    }
    for field_name, value in fields_to_check.items():
        value_lower = value.lower()
        for term in SUBJECT_TEXT_TERMS:
            if term in value_lower:
                failures.append(
                    f"SubjectBlock.{field_name} contains text-instruction "
                    f"phrase '{term}'. Text overlays are added separately. "
                    f"Remove from {field_name}."
                )
    return failures


def _check_brand_mood_coherence(ir: VisualPromptIR) -> list[str]:
    """Check both mood_descriptor and emotional_anchor against brand mood."""
    brand_mood = ir.brand.mood.lower()
    brand_cluster = _mood_to_cluster(brand_mood)
    if brand_cluster is None:
        return []

    failures: list[str] = []
    opposing_pairs = (
        ("warm", "clinical"),
        ("warm", "gritty"),
        ("aspirational", "gritty"),
    )

    subject_mood = ir.subject.mood_descriptor.lower()
    subject_cluster = _mood_to_cluster(subject_mood)
    if subject_cluster:
        for a, b in opposing_pairs:
            if {subject_cluster, brand_cluster} == {a, b}:
                failures.append(
                    f"Brand mood '{ir.brand.mood}' (cluster: {brand_cluster}) and "
                    f"subject mood_descriptor '{ir.subject.mood_descriptor}' "
                    f"(cluster: {subject_cluster}) are in opposing emotional clusters."
                )
                break

    if ir.subject.emotional_anchor:
        anchor_cluster = _mood_to_cluster(ir.subject.emotional_anchor.lower())
        if anchor_cluster:
            for a, b in opposing_pairs:
                if {anchor_cluster, brand_cluster} == {a, b}:
                    failures.append(
                        f"Brand mood '{ir.brand.mood}' (cluster: {brand_cluster}) "
                        f"and subject emotional_anchor '{ir.subject.emotional_anchor}' "
                        f"(cluster: {anchor_cluster}) are in opposing emotional clusters."
                    )
                    break

    return failures


def _check_color_palette_size(ir: VisualPromptIR) -> list[str]:
    n = len(ir.brand.color_palette)
    if n == 0:
        return [
            "BrandBlock.color_palette is empty. Image will use Flux defaults "
            "and won't reflect brand. Add 1-5 colors from BrandBible."
        ]
    if n > 5:
        return [
            f"BrandBlock.color_palette has {n} colors. More than 5 produces "
            f"muddy output. Trim to 3-4 most representative colors."
        ]
    return []


def _check_negative_block_completeness(ir: VisualPromptIR) -> list[str]:
    critical_avoids = {"text in image", "watermark", "distorted hands or faces"}
    avoid_set = {term.lower() for term in ir.negative.avoid_terms}
    missing = critical_avoids - avoid_set
    if missing:
        return [
            f"NegativeBlock missing critical anti-patterns: {sorted(missing)}. "
            f"These are nearly always wanted unless the brand intentionally "
            f"uses them. Re-add or confirm intentional override."
        ]
    return []


def _check_aspect_ratio_consistency(ir: VisualPromptIR) -> list[str]:
    try:
        expected = get_aspect_ratio(ir.platform.platform, ir.platform.content_type)
    except ValueError:
        return []

    if ir.platform.aspect_ratio != expected:
        return [
            f"PlatformBlock.aspect_ratio is {ir.platform.aspect_ratio.value} "
            f"but canonical mapping for ({ir.platform.platform}, "
            f"{ir.platform.content_type}) is {expected.value}. Confirm "
            f"intentional override or regenerate with default."
        ]
    return []


def _mood_to_cluster(mood_text: str) -> str | None:
    mood_lower = mood_text.lower()
    for cluster_name, keywords in MOOD_CLUSTERS.items():
        if any(kw in mood_lower for kw in keywords):
            return cluster_name
    return None


# ============================================================================
# End of consolidated visual module v2.0
# ============================================================================
