// PR #26 — Sprint 3: Auto-Generate Brand Bible.
//
// POST /api/brand-bible/apply-generated
//
// Coerces an AutoGeneratedBrandBible draft into the canonical
// BrandBible shape (projects.brand_context jsonb) and merges it into
// the existing bible if there is one.
//
// CRITICAL: We MERGE rather than replace so the user doesn't lose
// hand-curated fields (preferred terms, banned terms, non-negotiables,
// quote vault entries from PR #11, etc) when they apply a regenerated
// draft. The generated bible only overrides the slots it actually
// fills — archetype, voice, pillars, audience description — and
// non-empty quoteVault gets appended (deduped) to brand phrases.
import { createClient } from '@/lib/supabase/server';
import { db } from '@/lib/db';
import { projects } from '@/lib/db/schema';
import { eq, and } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import {
  computeCompletionScore,
  EMPTY_VOICE,
  type Archetype,
  type BrandBible,
  type BrandPillar,
} from '@/lib/types/brand';
import type { AutoGeneratedBrandBible } from '@/lib/brand-bible/auto-generate';

const ARCHETYPES: Archetype[] = [
  'hero',
  'sage',
  'outlaw',
  'creator',
  'caregiver',
  'magician',
  'ruler',
  'jester',
  'everyman',
  'lover',
  'innocent',
  'explorer',
];

function normalizeArchetype(input: string): Archetype | null {
  const lower = input.toLowerCase();
  return (ARCHETYPES as string[]).includes(lower) ? (lower as Archetype) : null;
}

// Generated voice scores are 0-100; canonical BrandBible voice is 0-10.
function voiceFromScore(score: number): number {
  return Math.max(0, Math.min(10, Math.round(score / 10)));
}

function pillarsFromStrings(names: string[]): BrandPillar[] {
  return names.map((name) => ({
    name,
    description: '',
    weight: 50,
  }));
}

function emptyBible(): BrandBible {
  return {
    identity: {
      name: null,
      tagline: null,
      mission: null,
      vision: null,
      foundedYear: null,
      industry: null,
    },
    archetype: { primary: null, secondary: null, rationale: null },
    pillars: [],
    voice: { ...EMPTY_VOICE },
    vocabulary: {
      preferredTerms: [],
      bannedTerms: [],
      brandPhrases: [],
      emojiPolicy: 'tasteful',
      hashtagPolicy: 'minimal',
    },
    nonNegotiables: [],
    audience: {
      primary: {
        description: '',
        demographics: null,
        psychographics: null,
        painPoints: [],
        jobsToBeDone: [],
        toolsTried: [],
        wateringHoles: [],
      },
      antiPersona: { description: null, reasons: [] },
    },
    messaging: {
      primaryTagline: null,
      taglineVariants: [],
      valueProps: [],
      objections: [],
      antiPositioning: [],
    },
    visual: {
      colors: { primary: null, secondary: null, accent: null, neutral: null },
      typography: { headingStyle: null, bodyStyle: null },
      imageStyle: null,
      photographyMood: null,
    },
    culturalMoments: [],
    meta: {
      autoDiscoveredAt: null,
      lastEditedAt: null,
      completionScore: 0,
      sourceUrls: [],
      confidence: {
        identity: 'inferred',
        archetype: 'inferred',
        pillars: 'inferred',
        voice: 'inferred',
        audience: 'inferred',
        messaging: 'inferred',
      },
    },
  };
}

function mergeGenerated(
  existing: BrandBible | null,
  generated: AutoGeneratedBrandBible
): BrandBible {
  const base = existing ?? emptyBible();
  const archetypePrimary = normalizeArchetype(generated.archetype);

  // Merge brand phrases: dedupe (case-insensitive trim) and cap at 50
  // so we don't grow the column unbounded across repeated regenerations.
  const existingPhrases = base.vocabulary?.brandPhrases ?? [];
  const seen = new Set(existingPhrases.map((p) => p.trim().toLowerCase()));
  const newPhrases: string[] = [];
  for (const q of generated.quoteVault) {
    const key = q.trim().toLowerCase();
    if (key && !seen.has(key)) {
      seen.add(key);
      newPhrases.push(q.trim());
    }
  }
  const mergedPhrases = [...existingPhrases, ...newPhrases].slice(0, 50);

  // Confidence: if the model said "high" we promote those fields to
  // 'medium' (we never claim user-level 'high' for AI-derived data).
  // Anything else stays 'inferred'.
  const inferredConfidence: 'medium' | 'inferred' =
    generated.confidence === 'high' ? 'medium' : 'inferred';

  const merged: BrandBible = {
    ...base,
    archetype: {
      primary: archetypePrimary ?? base.archetype.primary,
      secondary: base.archetype.secondary,
      rationale: generated.archetypeReasoning || base.archetype.rationale,
    },
    pillars:
      generated.pillars.length > 0
        ? pillarsFromStrings(generated.pillars)
        : base.pillars,
    voice: {
      ...base.voice,
      formal: voiceFromScore(generated.voiceCasualFormal),
      serious: voiceFromScore(generated.voicePlayfulSerious),
      bold: voiceFromScore(generated.voiceReservedBold),
      innovative: voiceFromScore(generated.voiceTraditionalInnovative),
    },
    vocabulary: {
      preferredTerms: base.vocabulary?.preferredTerms ?? [],
      bannedTerms: base.vocabulary?.bannedTerms ?? [],
      brandPhrases: mergedPhrases,
      emojiPolicy: base.vocabulary?.emojiPolicy ?? 'tasteful',
      hashtagPolicy: base.vocabulary?.hashtagPolicy ?? 'minimal',
    },
    audience: {
      ...base.audience,
      primary: {
        ...base.audience.primary,
        description:
          generated.audienceDescription || base.audience.primary.description,
        demographics:
          generated.audienceDemographics ||
          base.audience.primary.demographics,
      },
    },
    meta: {
      ...base.meta,
      autoDiscoveredAt: new Date().toISOString(),
      lastEditedAt: new Date().toISOString(),
      confidence: {
        identity: base.meta.confidence?.identity ?? 'inferred',
        archetype: archetypePrimary
          ? inferredConfidence
          : base.meta.confidence?.archetype ?? 'inferred',
        pillars:
          generated.pillars.length > 0
            ? inferredConfidence
            : base.meta.confidence?.pillars ?? 'inferred',
        voice: inferredConfidence,
        audience: generated.audienceDescription
          ? inferredConfidence
          : base.meta.confidence?.audience ?? 'inferred',
        messaging: base.meta.confidence?.messaging ?? 'inferred',
      },
      completionScore: 0, // recalculated below
    },
    // Cambio A — wow anchors. Non-empty generator output wins;
    // empty string preserves whatever the founder had set
    // manually before autogenerate fired.
    valueProp: generated.valueProp || base.valueProp,
    primaryPain: generated.primaryPain || base.primaryPain,
  };

  merged.meta.completionScore = computeCompletionScore(merged);
  return merged;
}

export async function POST(request: Request) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const body = await request.json().catch(() => ({}));
  const { projectId, brandBible: generated } = body as {
    projectId?: string;
    brandBible?: AutoGeneratedBrandBible;
  };

  if (!projectId || !generated) {
    return NextResponse.json(
      { error: 'projectId and brandBible required' },
      { status: 400 }
    );
  }

  const [project] = await db
    .select()
    .from(projects)
    .where(and(eq(projects.id, projectId), eq(projects.userId, user.id)))
    .limit(1);
  if (!project) {
    return NextResponse.json({ error: 'Project not found' }, { status: 404 });
  }

  const existing = (project.brandContext as BrandBible | null) ?? null;
  const merged = mergeGenerated(existing, generated);

  await db
    .update(projects)
    .set({ brandContext: merged })
    .where(eq(projects.id, projectId));

  return NextResponse.json({ success: true, brandBible: merged });
}
