// PR Sprint onboarding-wow — Cambio B helper.
//
// POST /api/brand-bible/quickstart
//
// One-shot orchestrator that powers the "✨ Autogenerate from
// your website" button in /onboarding/brand. Combines what would
// otherwise be 3 sequential client calls:
//
//   1. scrape project.domain (lib/brand-bible/web-scraper)
//   2. derive AutoGeneratedBrandBible via Opus
//      (lib/brand-bible/auto-generate)
//   3. merge + persist into projects.brand_context
//      (mirrors /api/brand-bible/apply-generated's mergeGenerated)
//
// Doing it server-side gives the founder one round-trip + lets
// the rate-limit live in a single place. Anonymous landing-page
// flow uses /api/landing/preview-bible (returns bible without
// persisting); this endpoint is the authenticated "save it to
// my project" counterpart.
//
// Body: { projectId }
// Returns: { success, brandBible }   (the persisted BrandBible)

import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { db } from '@/lib/db';
import { projects } from '@/lib/db/schema';
import { eq, and } from 'drizzle-orm';
import { checkRateLimit } from '@/lib/rate-limit';
import { scrapeWebsite } from '@/lib/brand-bible/web-scraper';
import {
  generateBrandBibleFromSources,
  type SourceForGeneration,
} from '@/lib/brand-bible/auto-generate';
import type { BrandBible } from '@/lib/types/brand';
import * as Sentry from '@sentry/nextjs';

// scrape (~3s) + Opus (~20-40s) — match the auto-generate route.
export const maxDuration = 90;

export async function POST(request: Request) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  // 5/hour/user — each call costs ~$0.05-0.10 in Opus. Generous
  // enough for honest iteration, tight enough to catch runaway
  // refreshes.
  const limit = checkRateLimit(`bible-quickstart:${user.id}`, 5, 60 * 60 * 1000);
  if (!limit.allowed) {
    return NextResponse.json(
      {
        error: 'Rate limit exceeded',
        hint: `Try again in ${Math.ceil(limit.resetMs / 60000)} minutes.`,
      },
      { status: 429 },
    );
  }

  let body: { projectId?: string };
  try {
    body = (await request.json()) as { projectId?: string };
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 });
  }
  const projectId = body.projectId;
  if (!projectId) {
    return NextResponse.json(
      { error: 'projectId required' },
      { status: 400 },
    );
  }

  // Ownership + read the project's domain.
  const [project] = await db
    .select()
    .from(projects)
    .where(and(eq(projects.id, projectId), eq(projects.userId, user.id)))
    .limit(1);
  if (!project) {
    return NextResponse.json({ error: 'Project not found' }, { status: 404 });
  }

  // The "+ Add project" modal records the URL into either
  // brand_url or domain depending on the codepath; check both.
  const urlCandidate = (project.brandUrl ?? project.domain ?? '').trim();
  if (!urlCandidate) {
    return NextResponse.json(
      {
        error:
          'Project has no website URL. Add one before autogenerating the brand bible.',
      },
      { status: 400 },
    );
  }
  const url = /^https?:\/\//i.test(urlCandidate)
    ? urlCandidate
    : `https://${urlCandidate}`;

  try {
    // 1. Scrape.
    const scraped = await scrapeWebsite(url);
    const websiteSource: SourceForGeneration = {
      type: 'website',
      data: scraped,
    };

    // 2. Opus → AutoGeneratedBrandBible (includes valueProp +
    // primaryPain per Cambio A).
    const generated = await generateBrandBibleFromSources(
      [websiteSource],
      project.name ?? 'Your brand',
    );

    // 3. Merge into existing brand_context. We keep it light here
    // (vs apply-generated's deep merge) because quickstart is
    // about establishing the FIRST bible — there's rarely an
    // existing one to preserve. Reuse the apply-generated logic
    // by re-issuing an internal fetch would be cleaner; for now
    // we shallow-merge so the persisted shape mirrors what
    // /onboarding/wow expects to read.
    const existing = (project.brandContext as BrandBible | null) ?? null;
    const merged: BrandBible = {
      identity: {
        name: existing?.identity?.name ?? project.name ?? null,
        tagline: existing?.identity?.tagline ?? null,
        mission: existing?.identity?.mission ?? null,
        vision: existing?.identity?.vision ?? null,
        foundedYear: existing?.identity?.foundedYear ?? null,
        industry: existing?.identity?.industry ?? null,
      },
      archetype: {
        primary:
          (generated.archetype.toLowerCase() as
            | BrandBible['archetype']['primary']
            | string) ===
          existing?.archetype?.primary
            ? (existing?.archetype?.primary ?? null)
            : ((generated.archetype.toLowerCase() ||
                existing?.archetype?.primary ||
                null) as BrandBible['archetype']['primary']),
        secondary: existing?.archetype?.secondary ?? null,
        rationale:
          generated.archetypeReasoning || existing?.archetype?.rationale || null,
      },
      pillars:
        generated.pillars.length > 0
          ? generated.pillars.map((name, i) => ({
              name,
              description: '',
              weight: 100 - i * 10,
            }))
          : existing?.pillars ?? [],
      voice: {
        formal: Math.round(generated.voiceCasualFormal / 10),
        serious: Math.round(generated.voicePlayfulSerious / 10),
        bold: Math.round(generated.voiceReservedBold / 10),
        innovative: Math.round(generated.voiceTraditionalInnovative / 10),
        approachable: existing?.voice?.approachable ?? 5,
      },
      vocabulary: existing?.vocabulary ?? {
        preferredTerms: [],
        bannedTerms: [],
        brandPhrases: [],
        emojiPolicy: 'tasteful',
        hashtagPolicy: 'minimal',
      },
      nonNegotiables: existing?.nonNegotiables ?? [],
      audience: {
        primary: {
          description:
            generated.audienceDescription ||
            existing?.audience?.primary?.description ||
            '',
          demographics:
            generated.audienceDemographics ||
            existing?.audience?.primary?.demographics ||
            null,
          // Keep the existing detail blocks when present; the quickstart
          // pipeline doesn't currently surface psychographics /
          // jobsToBeDone / wateringHoles from a single-page scrape, but
          // we must satisfy the BrandPrimaryAudience contract so the
          // jsonb shape stays canonical.
          psychographics: existing?.audience?.primary?.psychographics ?? null,
          painPoints: existing?.audience?.primary?.painPoints ?? [],
          jobsToBeDone: existing?.audience?.primary?.jobsToBeDone ?? [],
          toolsTried: existing?.audience?.primary?.toolsTried ?? [],
          wateringHoles: existing?.audience?.primary?.wateringHoles ?? [],
        },
        antiPersona: existing?.audience?.antiPersona ?? {
          description: null,
          reasons: [],
        },
      },
      messaging: existing?.messaging ?? {
        primaryTagline: null,
        taglineVariants: [],
        valueProps: [],
        objections: [],
        antiPositioning: [],
      },
      visual: existing?.visual ?? {
        colors: { primary: null, secondary: null, accent: null, neutral: null },
        typography: { headingStyle: null, bodyStyle: null },
        imageStyle: null,
        photographyMood: null,
      },
      culturalMoments: existing?.culturalMoments ?? [],
      meta: {
        autoDiscoveredAt: new Date().toISOString(),
        lastEditedAt: new Date().toISOString(),
        completionScore: existing?.meta?.completionScore ?? 0,
        sourceUrls: [url],
        confidence: existing?.meta?.confidence ?? {
          identity: 'inferred',
          archetype: 'inferred',
          pillars: 'inferred',
          voice: 'inferred',
          audience: 'inferred',
          messaging: 'inferred',
        },
      },
      // Cambio A — wow anchors. Generator output wins; empty
      // strings preserve any existing manual value.
      valueProp: generated.valueProp || existing?.valueProp,
      primaryPain: generated.primaryPain || existing?.primaryPain,
    };

    await db
      .update(projects)
      .set({ brandContext: merged })
      .where(eq(projects.id, projectId));

    return NextResponse.json({
      success: true,
      brandBible: merged,
    });
  } catch (e) {
    Sentry.captureException(e, {
      tags: { area: 'brand-bible', kind: 'quickstart-failed' },
      extra: { projectId, urlCandidate },
    });
    return NextResponse.json(
      {
        error: e instanceof Error ? e.message : 'Quickstart failed',
      },
      { status: 502 },
    );
  }
}
