// PR Sprint 7.19 — VisualPromptIR schema port.
//
// 1:1 translation of
// Helm SEO/helm-adaptive-voice-engine/visual_schema.py.
// Pydantic v2 → Zod. Same field types, same length constraints,
// same custom validators (no-text-instructions in main_subject,
// metaphor required when strategy=metaphor_driven).
//
// The IR is renderer-agnostic — visual-renderer-flux.ts is the
// only renderer in v1, but the shape supports Midjourney, SDXL,
// Imagen renderers without touching the IR or upstream pipeline.

import { z } from 'zod';

// ============================================================
// Enums
// ============================================================

// Top-level visual style category. Drives the renderer's style
// lead phrase.
export const STYLE_TYPES = [
  'photography',
  'illustration',
  'screenshot',
  'mixed_media',
  'abstract',
  '3d_render',
] as const;
export const StyleTypeSchema = z.enum(STYLE_TYPES);
export type StyleType = z.infer<typeof StyleTypeSchema>;

// Camera framing / lens choice.
export const CAMERA_TYPES = [
  'close-up',
  'medium shot',
  'wide shot',
  'overhead shot',
  'dutch angle',
  'macro lens',
  '85mm portrait lens',
  'documentary handheld',
  'flat lay top-down',
] as const;
export const CameraTypeSchema = z.enum(CAMERA_TYPES);
export type CameraType = z.infer<typeof CameraTypeSchema>;

// Lighting setup. One of the highest-impact knobs in image gen.
export const LIGHTING_TYPES = [
  'natural soft light',
  'golden hour warm light',
  'studio lighting with key + fill',
  'harsh dramatic shadows',
  'neon glow accent',
  'flat overhead lighting',
  'low-key moody lighting',
  'backlit silhouette',
  'soft window light',
] as const;
export const LightingTypeSchema = z.enum(LIGHTING_TYPES);
export type LightingType = z.infer<typeof LightingTypeSchema>;

// Aspect ratios. Mapped per (platform, content_type) in
// platform-visual-language.ts.
export const ASPECT_RATIOS = [
  '1:1',
  '4:5',
  '9:16',
  '16:9',
  '3:2',
] as const;
export const AspectRatioSchema = z.enum(ASPECT_RATIOS);
export type AspectRatio = z.infer<typeof AspectRatioSchema>;

// Depth of field. Shallow reads cinematic; deep focus reads
// documentary.
export const DEPTH_OF_FIELDS = [
  'shallow depth of field with bokeh background',
  'medium depth of field',
  'deep focus, everything sharp',
] as const;
export const DepthOfFieldSchema = z.enum(DEPTH_OF_FIELDS);
export type DepthOfField = z.infer<typeof DepthOfFieldSchema>;

// The high-level approach the visual takes. Output by the
// subject extractor; informs validation and the v1.5 learning
// loop weighting.
export const VISUAL_STRATEGIES = [
  'human_story', // Person in a real moment. Default for SaaS/founder content.
  'metaphor_driven', // Concrete object/scene representing an abstract concept.
  'product_shot', // The product / interface is the hero. Use sparingly.
  'data_visualization', // Chart, graph, screenshot. Only when data IS the story.
  'behind_scenes', // Workspace, process, in-progress moment.
  'brand_heritage', // Brand-anchored imagery (founder portrait, signature setting).
] as const;
export const VisualStrategySchema = z.enum(VISUAL_STRATEGIES);
export type VisualStrategy = z.infer<typeof VisualStrategySchema>;

// ============================================================
// Default negative terms
// ============================================================

// Anti-patterns for AI image generation. These avoid the most
// common tell-tale signs of generative output. Override per-
// client when the brand legitimately uses one of these styles.
export const DEFAULT_NEGATIVE_TERMS: ReadonlyArray<string> = [
  'text in image',
  'watermark',
  'logo overlay',
  'oversaturated colors',
  'plastic-looking skin',
  'distorted hands or faces',
  'extra fingers',
  'AI illustration aesthetic',
  'generic stock imagery',
  'amateur lighting',
  'blurry low quality',
  'cropped subject',
];

// ============================================================
// Building blocks
// ============================================================

// Phrases that, if present in main_subject, indicate the caller
// is trying to bake text overlays into the image. Text overlays
// are added separately in post-production.
const SUBJECT_TEXT_INSTRUCTION_PHRASES = [
  'with text',
  'with caption',
  'text overlay',
  'text saying',
  'watermark',
  'logo overlay',
] as const;

// What is IN the image. Generated by visual-subject-extractor.ts
// via a mini-LLM call that translates PAIN_POINT + caption into
// a concrete visual subject. This is the core innovation of the
// pipeline — without it, the model receives the caption (which
// describes the post, not the image) and has to guess.
export const SubjectBlockSchema = z
  .object({
    main_subject: z
      .string()
      .min(15, 'main_subject must be at least 15 chars')
      .max(300, 'main_subject must be at most 300 chars'),
    composition: z
      .string()
      .min(5, 'composition must be at least 5 chars')
      .max(150, 'composition must be at most 150 chars'),
    setting: z
      .string()
      .min(5, 'setting must be at least 5 chars')
      .max(200, 'setting must be at most 200 chars'),
    mood_descriptor: z
      .string()
      .min(3, 'mood_descriptor must be at least 3 chars')
      .max(80, 'mood_descriptor must be at most 80 chars'),
    emotional_anchor: z.string().max(30).nullable().optional(),
    visual_strategy: VisualStrategySchema,
    visual_metaphor: z.string().max(200).nullable().optional(),
  })
  .strict()
  .superRefine((subj, ctx) => {
    // 1. main_subject should not bake text overlay instructions.
    const lower = subj.main_subject.toLowerCase();
    for (const phrase of SUBJECT_TEXT_INSTRUCTION_PHRASES) {
      if (lower.includes(phrase)) {
        ctx.addIssue({
          code: 'custom',
          message: `main_subject contains text-instruction phrase '${phrase}'. Text overlays are added separately in post-production. Describe only the visual subject.`,
          path: ['main_subject'],
        });
      }
    }
    // 2. metaphor_driven requires visual_metaphor.
    if (
      subj.visual_strategy === 'metaphor_driven' &&
      (!subj.visual_metaphor || subj.visual_metaphor.trim().length === 0)
    ) {
      ctx.addIssue({
        code: 'custom',
        message:
          "visual_metaphor is required when visual_strategy is 'metaphor_driven'. Either set a metaphor or pick a different visual_strategy (e.g., 'human_story' for SaaS/founder pain points).",
        path: ['visual_metaphor'],
      });
    }
  });
export type SubjectBlock = z.infer<typeof SubjectBlockSchema>;

// How the image is rendered: photography vs illustration,
// camera, lighting.
export const StyleBlockSchema = z
  .object({
    style_type: StyleTypeSchema,
    camera: CameraTypeSchema.nullable().optional(),
    lighting: LightingTypeSchema.nullable().optional(),
    depth_of_field: DepthOfFieldSchema.nullable().optional(),
    additional_style_notes: z.string().max(200).nullable().optional(),
  })
  .strict();
export type StyleBlock = z.infer<typeof StyleBlockSchema>;

// Brand-specific visual identity. Pulled from BrandBible.visual.
export const BrandBlockSchema = z
  .object({
    archetype: z.string().min(2).max(50),
    mood: z.string().min(3).max(100),
    color_palette: z.array(z.string()).max(5).default([]),
    voice_descriptor: z.string().max(100).nullable().optional(),
  })
  .strict();
export type BrandBlock = z.infer<typeof BrandBlockSchema>;

// Platform-specific visual conventions.
export const PlatformBlockSchema = z
  .object({
    platform: z.string(),
    content_type: z.string(),
    aspect_ratio: AspectRatioSchema,
    visual_language_notes: z.string().min(10).max(400),
  })
  .strict();
export type PlatformBlock = z.infer<typeof PlatformBlockSchema>;

// Things the image should NOT contain. Renderer-specific syntax
// handled in the renderer.
export const NegativeBlockSchema = z
  .object({
    avoid_terms: z
      .array(z.string())
      .min(1)
      .max(20)
      .default([...DEFAULT_NEGATIVE_TERMS]),
  })
  .strict();
export type NegativeBlock = z.infer<typeof NegativeBlockSchema>;

// ============================================================
// Metadata
// ============================================================

export const VisualPromptMetadataSchema = z
  .object({
    pain_point_excerpt: z.string().max(300),
    caption_excerpt: z.string().max(300),
    target_platform: z.string(),
    target_content_type: z.string(),
    subject_extractor_model: z.string().nullable().optional(),
    subject_extractor_latency_ms: z.number().int().nullable().optional(),
    // Reserved for v1.5 SubjectBlock cache layer. Generated by
    // build_visual_prompt_ir().
    cache_key: z.string().nullable().optional(),
  })
  .strict();
export type VisualPromptMetadata = z.infer<typeof VisualPromptMetadataSchema>;

// ============================================================
// VisualPromptIR (top-level)
// ============================================================

// Pipeline:
//   1. build_visual_prompt_ir(...)        → IR
//   2. validate_visual_prompt_ir(ir)      → soft-check failures
//   3. render_for_flux(ir)                → Flux prompt string
//      OR render_for_<other>(ir)          → future renderers
export const VisualPromptIRSchema = z
  .object({
    subject: SubjectBlockSchema,
    style: StyleBlockSchema,
    brand: BrandBlockSchema,
    platform: PlatformBlockSchema,
    negative: NegativeBlockSchema.default({
      avoid_terms: [...DEFAULT_NEGATIVE_TERMS],
    }),
    metadata: VisualPromptMetadataSchema,
  })
  .strict();
export type VisualPromptIR = z.infer<typeof VisualPromptIRSchema>;
