"""
visual_schema.py
================

Pydantic models for the visual generation pipeline (Helm Adaptive Voice
Engine v1.0).

Defines the VisualPromptIR (intermediate representation) and its 5 building
blocks: SubjectBlock, StyleBlock, BrandBlock, PlatformBlock, NegativeBlock.

The IR is renderer-agnostic. visual_renderer_flux.py converts it to a Flux/
fal.ai prompt string. Future renderers (Midjourney, SDXL, Imagen) can be
added without touching the IR or the upstream pipeline.

Architectural notes:
  - SubjectBlock is the only block that requires a mini-LLM call to populate
    (visual_subject_extractor.py). All others are derived from BrandBible +
    static lookup tables.
  - PlatformBlock content comes from PLATFORM_VISUAL_LANGUAGE in
    platform_visual_language.py.
  - NegativeBlock has sane defaults for AI-image anti-patterns. Override
    per-client when needed (e.g., illustration-first brands don't want
    "AI illustration aesthetic" in the negative list).

Dependencies:
  - pydantic >= 2.0

Version: 1.0 (MVP Phase 1)
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


# ============================================================================
# Enums
# ============================================================================

class StyleType(str, Enum):
    """Top-level visual style category. Drives the renderer's style lead."""
    PHOTOGRAPHY = "photography"
    ILLUSTRATION = "illustration"
    SCREENSHOT = "screenshot"
    MIXED_MEDIA = "mixed_media"
    ABSTRACT = "abstract"
    THREE_D_RENDER = "3d_render"


class CameraType(str, Enum):
    """Camera framing / lens choice. Drives composition and feel."""
    CLOSE_UP = "close-up"
    MEDIUM_SHOT = "medium shot"
    WIDE_SHOT = "wide shot"
    OVERHEAD = "overhead shot"
    DUTCH_ANGLE = "dutch angle"
    MACRO = "macro lens"
    PORTRAIT_85MM = "85mm portrait lens"
    DOCUMENTARY = "documentary handheld"
    FLAT_LAY = "flat lay top-down"


class LightingType(str, Enum):
    """Lighting setup. One of the highest-impact knobs in image generation."""
    NATURAL_SOFT = "natural soft light"
    GOLDEN_HOUR = "golden hour warm light"
    STUDIO = "studio lighting with key + fill"
    HARSH_SHADOWS = "harsh dramatic shadows"
    NEON = "neon glow accent"
    OVERHEAD_FLAT = "flat overhead lighting"
    LOW_KEY = "low-key moody lighting"
    BACKLIT = "backlit silhouette"
    WINDOW_LIGHT = "soft window light"


class AspectRatio(str, Enum):
    """Aspect ratios supported across platforms. Map per (platform, content_type)
    in PLATFORM_VISUAL_LANGUAGE."""
    SQUARE = "1:1"
    PORTRAIT_4_5 = "4:5"
    PORTRAIT_9_16 = "9:16"
    LANDSCAPE_16_9 = "16:9"
    LANDSCAPE_3_2 = "3:2"


class DepthOfField(str, Enum):
    """Depth of field. Shallow DOF reads cinematic; deep focus reads documentary."""
    SHALLOW = "shallow depth of field with bokeh background"
    MEDIUM = "medium depth of field"
    DEEP = "deep focus, everything sharp"


class VisualStrategy(str, Enum):
    """The high-level approach the visual takes. Output by the subject
    extractor; informs validation and future learning loop weighting.
    """
    HUMAN_STORY = "human_story"            # Subject is a person in a real moment. Default for SaaS/founder content.
    METAPHOR_DRIVEN = "metaphor_driven"    # Concrete object/scene representing an abstract concept.
    PRODUCT_SHOT = "product_shot"          # The product / interface is the hero. Use sparingly.
    DATA_VISUALIZATION = "data_visualization"  # Chart, graph, screenshot. Only when data IS the story.
    BEHIND_SCENES = "behind_scenes"        # Workspace, process, in-progress moment.
    BRAND_HERITAGE = "brand_heritage"      # Brand-anchored imagery (founder portrait, signature setting). Rare.


# ============================================================================
# Building blocks
# ============================================================================

class SubjectBlock(BaseModel):
    """What is IN the image. Generated by visual_subject_extractor.py via a
    mini-LLM call that translates PAIN_POINT + caption into a concrete visual
    subject.

    This is the core innovation of the visual pipeline. Without it, the model
    receives the caption (which describes the post, not the image) and has to
    guess what to draw.
    """
    model_config = ConfigDict(extra="forbid")

    main_subject: str = Field(..., min_length=15, max_length=300,
                              description="Concrete description of the central subject. "
                                          "E.g., 'A solo founder hunched over a laptop at 2am, "
                                          "8 browser tabs visible'.")
    composition: str = Field(..., min_length=5, max_length=150,
                             description="Framing and arrangement. E.g., 'centered, slight "
                                         "low angle, subject filling 60% of frame'.")
    setting: str = Field(..., min_length=5, max_length=200,
                         description="Environment / context. E.g., 'messy home office, "
                                     "warm desk lamp, late night'.")
    mood_descriptor: str = Field(..., min_length=3, max_length=80,
                                 description="Emotional tone, full phrase. "
                                             "E.g., 'exhausted but determined', "
                                             "'quietly confident', 'frustrated and overwhelmed'.")
    emotional_anchor: str | None = Field(default=None, max_length=30,
                                         description="Single dominant emotion as a short tag, "
                                                     "1-3 words max. E.g., 'exhaustion', "
                                                     "'determination', 'relief'. Different from "
                                                     "mood_descriptor (full phrase). Used for "
                                                     "filtering and learning loop clustering.")
    visual_strategy: VisualStrategy = Field(...,
                                            description="The high-level approach this visual "
                                                        "takes. Default for SaaS/founder content "
                                                        "is HUMAN_STORY.")
    visual_metaphor: str | None = Field(default=None, max_length=200,
                                        description="Required when visual_strategy is "
                                                    "METAPHOR_DRIVEN, otherwise null. "
                                                    "E.g., 'tabs as physical playing cards "
                                                    "scattered around'.")

    @field_validator("main_subject")
    @classmethod
    def no_text_instructions(cls, v: str) -> str:
        """Subject should describe the visual, not include text-overlay instructions."""
        bad_terms = ("with text", "with caption", "text overlay", "text saying",
                     "watermark", "logo overlay")
        v_lower = v.lower()
        for term in bad_terms:
            if term in v_lower:
                raise ValueError(
                    f"main_subject contains text-instruction phrase '{term}'. "
                    f"Text overlays are added separately in post-production. "
                    f"Describe only the visual subject."
                )
        return v

    @model_validator(mode="after")
    def metaphor_required_for_metaphor_driven(self) -> "SubjectBlock":
        """When visual_strategy is METAPHOR_DRIVEN, visual_metaphor must be set.
        For other strategies, visual_metaphor is optional and usually null.
        """
        if self.visual_strategy == VisualStrategy.METAPHOR_DRIVEN and not self.visual_metaphor:
            raise ValueError(
                "visual_metaphor is required when visual_strategy is METAPHOR_DRIVEN. "
                "Either set a metaphor or pick a different visual_strategy "
                "(e.g., HUMAN_STORY for SaaS/founder pain points)."
            )
        return self


class StyleBlock(BaseModel):
    """How the image is rendered: photography vs illustration, camera, lighting."""
    model_config = ConfigDict(extra="forbid")

    style_type: StyleType
    camera: CameraType | None = None
    lighting: LightingType | None = None
    depth_of_field: DepthOfField | None = None
    additional_style_notes: str | None = Field(default=None, max_length=200,
                                               description="Free-form additions: "
                                                           "'film grain', 'editorial polish', "
                                                           "'vintage 35mm', etc.")


class BrandBlock(BaseModel):
    """Brand-specific visual identity. Pulled from BrandBible.visual."""
    model_config = ConfigDict(extra="forbid")

    archetype: str = Field(..., min_length=2, max_length=50,
                           description="Brand archetype, e.g., 'rebel', 'sage', 'creator'.")
    mood: str = Field(..., min_length=3, max_length=100,
                      description="Photography mood from BrandBible, e.g., 'warm and human', "
                                  "'clean and minimal', 'gritty documentary'.")
    color_palette: list[str] = Field(default_factory=list, max_length=5,
                                     description="Hex codes or color names. Up to 5.")
    voice_descriptor: str | None = Field(default=None, max_length=100)


class PlatformBlock(BaseModel):
    """Platform-specific visual conventions for the target output type."""
    model_config = ConfigDict(extra="forbid")

    platform: str
    content_type: str
    aspect_ratio: AspectRatio
    visual_language_notes: str = Field(..., min_length=10, max_length=400,
                                       description="Platform-specific composition / mood / "
                                                   "treatment notes. E.g., 'mobile-first vertical "
                                                   "framing, ample negative space at top for UI'.")


# Default anti-patterns for AI image generation. These avoid the most common
# tell-tale signs of generative output. Override per-client if a brand
# legitimately uses one of these styles (e.g., illustration-first brands).
DEFAULT_NEGATIVE_TERMS: list[str] = [
    "text in image",
    "watermark",
    "logo overlay",
    "oversaturated colors",
    "plastic-looking skin",
    "distorted hands or faces",
    "extra fingers",
    "AI illustration aesthetic",
    "generic stock imagery",
    "amateur lighting",
    "blurry low quality",
    "cropped subject",
]


class NegativeBlock(BaseModel):
    """Things the image should NOT contain. Renderer-specific syntax handled
    in the renderer (Flux uses prose, Midjourney uses --no, SDXL uses
    negative_prompt field)."""
    model_config = ConfigDict(extra="forbid")

    avoid_terms: list[str] = Field(default_factory=lambda: list(DEFAULT_NEGATIVE_TERMS),
                                   min_length=1, max_length=20)


# ============================================================================
# Metadata
# ============================================================================

class VisualPromptMetadata(BaseModel):
    """Bookkeeping for downstream telemetry and audit."""
    model_config = ConfigDict(extra="forbid")

    pain_point_excerpt: str = Field(..., max_length=300,
                                    description="First 300 chars of the pain point that "
                                                "drove this generation. For audit.")
    caption_excerpt: str = Field(..., max_length=300,
                                 description="First 300 chars of the caption. For audit.")
    target_platform: str
    target_content_type: str
    subject_extractor_model: str | None = Field(default=None,
                                                description="Which model generated the SubjectBlock. "
                                                            "E.g., 'claude-haiku-4-5'.")
    subject_extractor_latency_ms: int | None = None
    cache_key: str | None = Field(default=None,
                                  description="Stable hash of (pain_point, caption, brand_archetype, "
                                              "brand_mood, platform, content_type). Reserved for v1.5 "
                                              "SubjectBlock cache layer. Generated by build_visual_prompt_ir().")


# ============================================================================
# VisualPromptIR (top-level)
# ============================================================================

class VisualPromptIR(BaseModel):
    """Intermediate representation of a visual prompt. Renderer-agnostic.

    Pipeline:
      1. visual_prompt_builder.build_visual_prompt_ir(...) produces this IR
      2. visual_validator.validate_visual_prompt_ir(ir) checks soft rules
      3. visual_renderer_flux.render_for_flux(ir) -> string for fal.ai
         OR visual_renderer_midjourney.render_for_midjourney(ir) -> string
         OR future renderers
    """
    model_config = ConfigDict(extra="forbid")

    subject: SubjectBlock
    style: StyleBlock
    brand: BrandBlock
    platform: PlatformBlock
    negative: NegativeBlock = Field(default_factory=NegativeBlock)
    metadata: VisualPromptMetadata
