// PR #26 — Sprint 3: Auto-Generate Brand Bible.
//
// Takes the per-source analysis blobs (currently just WebScrapingResult
// from web-scraper.ts; later FB / IG / etc) and asks Opus to derive a
// brand bible draft. The output is intentionally close-but-not-identical
// to the canonical BrandBible shape — the apply step (apply-generated)
// is what coerces these flat fields into the nested BrandBible
// structure.
//
// Why a separate intermediate shape?
//   1. The UI shows a confidence + discrepancies block that doesn't
//      live in BrandBible. Keeping those fields in this layer means
//      we don't pollute the canonical type.
//   2. Voice scores are 0-100 here (matches typical scale, easier to
//      reason about) but BrandBible.voice is 0-10. The mapping happens
//      in apply-generated.
import { anthropic } from '@/lib/ai/claude';
import type { WebScrapingResult } from './web-scraper';

export interface AutoGeneratedBrandBible {
  archetype: string; // one of the 12 standard archetypes
  archetypeReasoning: string;
  voiceCasualFormal: number; // 0=very casual, 100=very formal
  voicePlayfulSerious: number; // 0=playful, 100=serious
  voiceReservedBold: number; // 0=reserved, 100=bold
  voiceTraditionalInnovative: number; // 0=traditional, 100=innovative
  pillars: string[]; // 3-5 short pillars
  pillarsReasoning: string;
  audienceDescription: string;
  audienceDemographics: string;
  quoteVault: string[]; // 5-7 actual quotes from the sources
  // Onboarding wow moment anchors — Cambio A.
  //
  // Separate concern from messaging.valueProps[] (structured per-
  // pillar propositions for the generator). These two are
  // founder-voice single sentences used by the wowMode prompt in
  // /api/ai/generate-structured to produce specific copies
  // instead of "Empower your business" defaults.
  //
  // apply-generated maps these into BrandBible.valueProp +
  // BrandBible.primaryPain (both optional) at write-time.
  valueProp: string;
  primaryPain: string;
  discrepancies: Array<{
    type:
      | 'tone_mismatch'
      | 'visual_mismatch'
      | 'audience_mismatch'
      | 'value_mismatch';
    description: string;
    sources: string[];
  }>;
  confidence: 'low' | 'medium' | 'high';
  confidenceReasoning: string;
}

export interface SourceForGeneration {
  type: string; // 'website' | 'facebook_page' | …
  data: WebScrapingResult | unknown;
}

const VALID_ARCHETYPES = [
  'Magician',
  'Hero',
  'Sage',
  'Creator',
  'Caregiver',
  'Ruler',
  'Innocent',
  'Explorer',
  'Outlaw',
  'Lover',
  'Jester',
  'Everyman',
];

function buildWebsiteContext(s: SourceForGeneration): string {
  const data = s.data as WebScrapingResult;
  return `
WEBSITE: ${data.url}
Title: ${data.title || '(empty)'}
Meta description: ${data.metaDescription || '(empty)'}
Headlines: ${data.headlines.slice(0, 10).join(' | ') || '(none)'}
CTAs: ${data.ctaTexts.slice(0, 10).join(' | ') || '(none)'}
Body sample: ${data.bodyText.substring(0, 1500) || '(empty)'}
Tone signals: ${data.exclamationCount} exclamations, ${data.questionCount} questions, ${data.emojiCount} emojis, avg ${data.averageSentenceLength} words/sentence
Visual: primary color ${data.primaryColor || 'unknown'}, fonts ${data.fonts.join(', ') || 'unknown'}
OG tags: ${data.ogTitle ?? '—'} / ${data.ogDescription ?? '—'}
  `.trim();
}

function clamp(n: unknown, min: number, max: number, fallback: number): number {
  const num = Number(n);
  if (!Number.isFinite(num)) return fallback;
  return Math.max(min, Math.min(max, Math.round(num)));
}

function isString(v: unknown): v is string {
  return typeof v === 'string';
}

// Light validation: clamp scores into range, normalize archetype, drop
// non-string array entries. We don't reject on missing fields because
// Opus sometimes returns half-completes for low-evidence inputs and
// "low confidence + sparse fields" is more useful than an error.
function sanitize(raw: unknown): AutoGeneratedBrandBible {
  const r = (raw ?? {}) as Record<string, unknown>;
  const rawArch = isString(r.archetype) ? r.archetype : 'Sage';
  // Normalize case-insensitive matches against the 12 archetypes;
  // fall back to the model's text if it picked something off-list
  // (we'd rather show "MysteryArchetype" than crash).
  const archetype =
    VALID_ARCHETYPES.find((a) => a.toLowerCase() === rawArch.toLowerCase()) ??
    rawArch;

  const pillars = Array.isArray(r.pillars)
    ? r.pillars.filter(isString).slice(0, 5)
    : [];

  const quoteVault = Array.isArray(r.quoteVault)
    ? r.quoteVault.filter(isString).slice(0, 7)
    : [];

  const discrepancies = Array.isArray(r.discrepancies)
    ? r.discrepancies
        .map((d) => {
          const dd = (d ?? {}) as Record<string, unknown>;
          if (!isString(dd.type) || !isString(dd.description)) return null;
          return {
            type: dd.type as AutoGeneratedBrandBible['discrepancies'][number]['type'],
            description: dd.description,
            sources: Array.isArray(dd.sources)
              ? dd.sources.filter(isString)
              : [],
          };
        })
        .filter((d): d is AutoGeneratedBrandBible['discrepancies'][number] =>
          d !== null
        )
    : [];

  const confidenceRaw = isString(r.confidence) ? r.confidence : 'low';
  const confidence: AutoGeneratedBrandBible['confidence'] =
    confidenceRaw === 'high' || confidenceRaw === 'medium'
      ? confidenceRaw
      : 'low';

  return {
    archetype,
    archetypeReasoning: isString(r.archetypeReasoning)
      ? r.archetypeReasoning
      : '',
    voiceCasualFormal: clamp(r.voiceCasualFormal, 0, 100, 50),
    voicePlayfulSerious: clamp(r.voicePlayfulSerious, 0, 100, 50),
    voiceReservedBold: clamp(r.voiceReservedBold, 0, 100, 50),
    voiceTraditionalInnovative: clamp(
      r.voiceTraditionalInnovative,
      0,
      100,
      50
    ),
    pillars,
    pillarsReasoning: isString(r.pillarsReasoning) ? r.pillarsReasoning : '',
    audienceDescription: isString(r.audienceDescription)
      ? r.audienceDescription
      : '',
    audienceDemographics: isString(r.audienceDemographics)
      ? r.audienceDemographics
      : '',
    quoteVault,
    // Cambio A — wow anchors, soft-defaulted. Empty string is the
    // signal apply-generated uses to decide whether to populate
    // BrandBible.valueProp / primaryPain on write.
    valueProp: isString(r.valueProp) ? r.valueProp.slice(0, 500) : '',
    primaryPain: isString(r.primaryPain) ? r.primaryPain.slice(0, 500) : '',
    discrepancies,
    confidence,
    confidenceReasoning: isString(r.confidenceReasoning)
      ? r.confidenceReasoning
      : '',
  };
}

export async function generateBrandBibleFromSources(
  sources: SourceForGeneration[],
  projectName: string
): Promise<AutoGeneratedBrandBible> {
  const websiteSources = sources.filter((s) => s.type === 'website');
  const socialSources = sources.filter((s) => s.type !== 'website');

  const websiteContext =
    websiteSources.length > 0
      ? websiteSources.map(buildWebsiteContext).join('\n\n')
      : '(no website connected)';

  const socialContext =
    socialSources.length > 0
      ? socialSources
          .map(
            (s) =>
              `${s.type}: [data placeholder — Sprint 5 will fill this in once OAuth ships]`
          )
          .join('\n\n')
      : '(no social sources connected yet)';

  const prompt = `You are a brand strategist analyzing a company's existing presence to derive their brand bible.

PROJECT NAME: ${projectName}

═══ SOURCES TO ANALYZE ═══

${websiteContext}

${socialContext}

═══ TASK ═══

Analyze ALL sources and produce a brand bible. Be RIGOROUS, not generic. Use evidence from the actual content.

═══ OUTPUT FORMAT (strict JSON, no markdown fences) ═══

{
  "archetype": "one of: Magician, Hero, Sage, Creator, Caregiver, Ruler, Innocent, Explorer, Outlaw, Lover, Jester, Everyman",
  "archetypeReasoning": "1-2 sentences why this archetype fits, citing specific evidence",
  "voiceCasualFormal": <0-100, 0=super casual / 100=corporate formal>,
  "voicePlayfulSerious": <0-100, 0=playful / 100=dead serious>,
  "voiceReservedBold": <0-100, 0=reserved / 100=bold and confident>,
  "voiceTraditionalInnovative": <0-100, 0=traditional / 100=cutting edge>,
  "pillars": ["3-5 short pillars (1-3 words each)"],
  "pillarsReasoning": "why these pillars from the evidence",
  "audienceDescription": "specific audience description (NEVER 'everyone' or 'businesses')",
  "audienceDemographics": "concrete demographics if detectable from copy/imagery, else empty string",
  "quoteVault": ["5-7 ACTUAL EXACT quotes pulled from the sources that exemplify the voice"],
  "valueProp": "1-2 sentences in the FOUNDER'S OWN VOICE saying what makes this brand uncopiable. SPECIFIC to this project, NEVER generic phrases like 'empower your business' or 'streamline workflows'. If the source has a tagline that already says it well, use it verbatim. Empty string only if absolutely no signal.",
  "primaryPain": "The single most acute audience pain — ONE sentence, in the AUDIENCE'S own words when an analyzed source quoted it directly (look in the quoteVault items + body text for verbatim pain language). Empty string only if no pain signal in sources.",
  "discrepancies": [
    {
      "type": "tone_mismatch | visual_mismatch | audience_mismatch | value_mismatch",
      "description": "what's inconsistent across sources",
      "sources": ["which sources clash"]
    }
  ],
  "confidence": "low | medium | high",
  "confidenceReasoning": "why this confidence level given the evidence"
}

═══ RULES ═══

1. Use ACTUAL evidence from sources. NEVER invent data.
2. If only website is connected (no social), confidence is at most "medium".
3. If a field can't be determined, return an empty string or empty array. NEVER make up plausible-sounding fillers.
4. Quote vault must contain EXACT quotes from the body text or headlines, character-for-character. Do not paraphrase.
5. Discrepancies require 2+ sources to compare. With one source, discrepancies = [].
6. Voice scores: 50 = neutral. Scores far from 50 should have evidence.
7. NEVER default to generic indie-hacker / SaaS / startup descriptions. Be specific to THIS project.

Return only the JSON object — no preamble, no markdown fences.`;

  const response = await anthropic.messages.create({
    model: 'claude-opus-4-7',
    max_tokens: 4096,
    messages: [{ role: 'user', content: prompt }],
  });

  const textBlock = response.content.find((b) => b.type === 'text');
  let text = textBlock?.type === 'text' ? textBlock.text.trim() : '';

  // Strip ``` fences if Opus added them despite the instruction.
  if (text.startsWith('```')) {
    text = text
      .replace(/^```(?:json)?\s*/i, '')
      .replace(/\s*```\s*$/i, '')
      .trim();
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    throw new Error(
      'AI returned invalid JSON. Try again — sometimes Opus gets chatty on retries.'
    );
  }

  return sanitize(parsed);
}
