'use client';

// PR #26 — Sprint 3: Auto-Generate Brand Bible.
//
// The full UX surface for auto-generation. Used inside the Brand Bible
// modal as a new mode (`auto`). Three layers stacked here:
//   - SourcesList:      list of connected sources + "+ Add source"
//   - AddSourceModal:   pick platform + enter URL/handle
//   - PreviewModal:     review the generated bible before applying
//
// The platform picker shows Facebook / Instagram / LinkedIn / Twitter
// as "SOON" options — wired to nothing today; OAuth ships in Sprint 5.
// The user can still browse the list to validate that those connectors
// are coming.
import { useEffect, useState } from 'react';
import {
  Sparkles,
  Globe,
  Facebook,
  Instagram,
  Linkedin,
  Twitter,
  Loader2,
  Trash2,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { GlassCard } from '@/components/ui/glass-card';
import type { AutoGeneratedBrandBible } from '@/lib/brand-bible/auto-generate';

type SourceType =
  | 'website'
  | 'facebook_page'
  | 'instagram_business'
  | 'linkedin'
  | 'twitter';

interface SourceRow {
  id: string;
  projectId: string;
  userId: string;
  sourceType: SourceType;
  sourceUrl: string | null;
  sourceHandle: string | null;
  sourceExternalId: string | null;
  status: 'pending' | 'analyzing' | 'analyzed' | 'failed' | 'disconnected';
  lastAnalyzedAt: string | null;
  errorMessage: string | null;
  createdAt: string;
  updatedAt: string;
}

const SOURCE_PLATFORMS: Array<{
  value: SourceType;
  label: string;
  icon: typeof Globe;
  available: boolean;
}> = [
  { value: 'website', label: 'Website', icon: Globe, available: true },
  {
    value: 'facebook_page',
    label: 'Facebook',
    icon: Facebook,
    available: false,
  },
  {
    value: 'instagram_business',
    label: 'Instagram',
    icon: Instagram,
    available: false,
  },
  { value: 'linkedin', label: 'LinkedIn', icon: Linkedin, available: false },
  { value: 'twitter', label: 'Twitter / X', icon: Twitter, available: false },
];

const STATUS_LABEL: Record<SourceRow['status'], string> = {
  pending: 'Pending',
  analyzing: 'Analyzing',
  analyzed: 'Analyzed',
  failed: 'Failed',
  disconnected: 'Disconnected',
};

const STATUS_TINT: Record<SourceRow['status'], string> = {
  pending: 'text-text-3',
  analyzing: 'text-accent',
  analyzed: 'text-emerald-500',
  failed: 'text-danger',
  disconnected: 'text-text-3',
};

export function AutoGenerateSection({
  projectId,
  projectName,
  onApplied,
}: {
  projectId: string;
  projectName: string;
  // Called after the user clicks "Apply to project" so the parent
  // modal can refresh the bible state and bounce back to overview.
  onApplied: () => void;
}) {
  const [sources, setSources] = useState<SourceRow[]>([]);
  const [loadingSources, setLoadingSources] = useState(true);
  const [showAdd, setShowAdd] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [generated, setGenerated] = useState<AutoGeneratedBrandBible | null>(
    null
  );
  const [genError, setGenError] = useState<string | null>(null);

  const refetch = async () => {
    setLoadingSources(true);
    try {
      const res = await fetch(
        `/api/brand-bible/sources?projectId=${projectId}`
      );
      const data = (await res.json()) as { sources?: SourceRow[] };
      setSources(data.sources ?? []);
    } finally {
      setLoadingSources(false);
    }
  };

  useEffect(() => {
    if (projectId) refetch();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectId]);

  const analyzedCount = sources.filter((s) => s.status === 'analyzed').length;
  const canGenerate = analyzedCount > 0;

  const handleGenerate = async () => {
    setGenerating(true);
    setGenError(null);
    try {
      const res = await fetch('/api/brand-bible/auto-generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ projectId }),
      });
      const data = (await res.json()) as {
        success?: boolean;
        brandBible?: AutoGeneratedBrandBible;
        error?: string;
      };
      if (!res.ok || !data.success || !data.brandBible) {
        setGenError(data.error ?? 'Generation failed');
        return;
      }
      setGenerated(data.brandBible);
    } catch (e) {
      setGenError(e instanceof Error ? e.message : 'Network error');
    } finally {
      setGenerating(false);
    }
  };

  const applyGenerated = async () => {
    if (!generated) return;
    const res = await fetch('/api/brand-bible/apply-generated', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ projectId, brandBible: generated }),
    });
    if (!res.ok) {
      const data = await res.json().catch(() => ({}));
      setGenError(data?.error ?? 'Apply failed');
      return;
    }
    setGenerated(null);
    onApplied();
  };

  return (
    <div className="space-y-5">
      <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
        <div className="flex items-start gap-3">
          <Sparkles className="w-5 h-5 text-accent mt-0.5 shrink-0" />
          <div>
            <h3 className="font-display text-lg font-light mb-1">
              Auto-generate from your existing presence
            </h3>
            <p className="text-sm text-text-2 leading-relaxed">
              Connect channels and Helm analyzes the tone, audience, and
              voice for{' '}
              <span className="text-text-1 font-medium">{projectName}</span>.
              Apply when you&apos;re happy — your existing bible fields stay
              intact.
            </p>
          </div>
        </div>
        <Button
          size="sm"
          onClick={handleGenerate}
          disabled={!canGenerate || generating}
          className="self-start whitespace-nowrap"
        >
          {generating ? (
            <span className="flex items-center gap-2">
              <Loader2 className="w-4 h-4 animate-spin" />
              Generating…
            </span>
          ) : (
            <span className="flex items-center gap-2">
              <Sparkles className="w-4 h-4" />
              Generate brand bible
            </span>
          )}
        </Button>
      </div>

      {genError && (
        <div className="p-3 border border-danger/30 bg-danger/10 rounded-lg text-xs text-danger">
          {genError}
        </div>
      )}

      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <h4 className="text-[10px] font-mono uppercase tracking-[0.15em] text-text-3">
            Connected sources
          </h4>
          {analyzedCount > 0 && (
            <span className="text-[10px] font-mono text-text-3">
              {analyzedCount}/{sources.length} analyzed
            </span>
          )}
        </div>

        {loadingSources ? (
          <div className="text-xs text-text-3 py-4">Loading sources…</div>
        ) : sources.length === 0 ? (
          <div className="p-6 border border-dashed border-border rounded-lg text-center">
            <p className="text-sm text-text-2 mb-3">
              No sources connected yet. Add your website to start.
            </p>
            <Button size="sm" onClick={() => setShowAdd(true)}>
              + Add source
            </Button>
          </div>
        ) : (
          <>
            {sources.map((source) => (
              <SourceListItem
                key={source.id}
                source={source}
                onChange={refetch}
              />
            ))}
            <button
              type="button"
              onClick={() => setShowAdd(true)}
              className="w-full py-2 border border-dashed border-border rounded-lg text-xs text-text-3 hover:border-accent hover:text-accent transition-colors"
            >
              + Add another source
            </button>
          </>
        )}
      </div>

      {showAdd && (
        <AddSourceModal
          projectId={projectId}
          onClose={() => setShowAdd(false)}
          onAdded={() => {
            setShowAdd(false);
            refetch();
          }}
        />
      )}

      {generated && (
        <GeneratedPreviewModal
          generated={generated}
          onClose={() => setGenerated(null)}
          onApply={applyGenerated}
        />
      )}
    </div>
  );
}

function SourceListItem({
  source,
  onChange,
}: {
  source: SourceRow;
  onChange: () => void;
}) {
  const [busy, setBusy] = useState(false);

  const Icon =
    SOURCE_PLATFORMS.find((p) => p.value === source.sourceType)?.icon ?? Globe;

  const analyze = async () => {
    setBusy(true);
    try {
      await fetch(`/api/brand-bible/sources/${source.id}/analyze`, {
        method: 'POST',
      });
    } finally {
      onChange();
      setBusy(false);
    }
  };

  const remove = async () => {
    if (!confirm('Remove this source?')) return;
    setBusy(true);
    try {
      await fetch(`/api/brand-bible/sources/${source.id}`, {
        method: 'DELETE',
      });
    } finally {
      onChange();
    }
  };

  return (
    <div className="flex items-center justify-between gap-3 p-3 bg-bg-elev/50 border border-border rounded-lg">
      <div className="flex items-center gap-3 min-w-0 flex-1">
        <Icon className="w-4 h-4 text-text-3 shrink-0" />
        <div className="min-w-0 flex-1">
          <div className="text-sm font-medium capitalize truncate">
            {source.sourceType.replace('_', ' ')}
          </div>
          <div className="text-xs text-text-3 truncate">
            {source.sourceUrl ||
              source.sourceHandle ||
              source.sourceExternalId ||
              '—'}
          </div>
          {source.errorMessage && (
            <div className="text-[10px] text-danger truncate mt-0.5">
              ⚠ {source.errorMessage}
            </div>
          )}
        </div>
      </div>

      <div className="flex items-center gap-2 shrink-0">
        <span
          className={`text-[10px] font-mono uppercase tracking-[0.1em] ${STATUS_TINT[source.status]}`}
        >
          {STATUS_LABEL[source.status]}
        </span>

        {(source.status === 'pending' ||
          source.status === 'failed' ||
          source.status === 'analyzed') && (
          <Button
            size="sm"
            variant={source.status === 'analyzed' ? 'ghost' : 'primary'}
            onClick={analyze}
            disabled={busy}
          >
            {busy
              ? '…'
              : source.status === 'analyzed'
                ? 'Re-analyze'
                : 'Analyze'}
          </Button>
        )}

        <button
          type="button"
          onClick={remove}
          disabled={busy}
          className="p-2 text-text-3 hover:text-danger rounded transition-colors disabled:opacity-50"
          aria-label="Remove source"
          title="Remove source"
        >
          <Trash2 className="w-3.5 h-3.5" />
        </button>
      </div>
    </div>
  );
}

function AddSourceModal({
  projectId,
  onClose,
  onAdded,
}: {
  projectId: string;
  onClose: () => void;
  onAdded: () => void;
}) {
  const [sourceType, setSourceType] = useState<SourceType>('website');
  const [sourceUrl, setSourceUrl] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const submit = async () => {
    setSubmitting(true);
    setError(null);
    try {
      const res = await fetch('/api/brand-bible/sources', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          projectId,
          sourceType,
          sourceUrl: sourceType === 'website' ? sourceUrl : null,
        }),
      });
      const data = await res.json().catch(() => ({}));
      if (res.status === 501) {
        setError(
          data.error ??
            'OAuth para esta plataforma llega en Sprint 5. Por ahora solo Website está habilitado.'
        );
        return;
      }
      if (!res.ok) {
        setError(data.error ?? 'Could not add source');
        return;
      }
      onAdded();
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Network error');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div
      className="fixed inset-0 bg-black/60 z-[60] flex items-center justify-center p-4 backdrop-blur-sm"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div className="bg-bg-elev border border-border rounded-xl p-6 max-w-md w-full">
        <div className="flex items-start justify-between mb-4">
          <h3 className="font-display text-2xl font-light">Add a source</h3>
          <button
            type="button"
            onClick={onClose}
            className="text-text-3 hover:text-text-1 text-xl leading-none"
            aria-label="Close"
          >
            ×
          </button>
        </div>

        <div className="space-y-4">
          <div>
            <label className="text-[10px] font-mono uppercase tracking-[0.15em] text-text-3 mb-2 block">
              Platform
            </label>
            <div className="grid grid-cols-2 gap-2">
              {SOURCE_PLATFORMS.map((opt) => {
                const Icon = opt.icon;
                const active = sourceType === opt.value;
                return (
                  <button
                    key={opt.value}
                    type="button"
                    disabled={!opt.available}
                    onClick={() => opt.available && setSourceType(opt.value)}
                    className={`
                      p-3 border rounded-lg text-sm flex items-center gap-2 transition-colors
                      ${active ? 'border-accent bg-accent/10 text-accent' : 'border-border'}
                      ${!opt.available ? 'opacity-50 cursor-not-allowed' : 'hover:border-accent'}
                    `}
                  >
                    <Icon className="w-4 h-4" />
                    <span className="flex-1 text-left">{opt.label}</span>
                    {!opt.available && (
                      <span className="text-[9px] font-mono uppercase tracking-[0.1em] text-text-3">
                        Soon
                      </span>
                    )}
                  </button>
                );
              })}
            </div>
          </div>

          {sourceType === 'website' && (
            <div>
              <label className="text-[10px] font-mono uppercase tracking-[0.15em] text-text-3 mb-2 block">
                Website URL
              </label>
              <input
                type="url"
                placeholder="https://example.com"
                value={sourceUrl}
                onChange={(e) => setSourceUrl(e.target.value)}
                className="w-full px-3 py-2 bg-bg border border-border rounded-lg text-sm outline-none focus:border-accent"
                autoFocus
              />
            </div>
          )}

          {error && (
            <div className="p-3 border border-danger/30 bg-danger/10 rounded-lg text-xs text-danger">
              {error}
            </div>
          )}
        </div>

        <div className="flex justify-end gap-2 mt-6 pt-4 border-t border-border">
          <Button variant="ghost" size="sm" onClick={onClose}>
            Cancel
          </Button>
          <Button
            size="sm"
            onClick={submit}
            disabled={
              submitting || (sourceType === 'website' && !sourceUrl.trim())
            }
          >
            {submitting ? 'Adding…' : 'Add source'}
          </Button>
        </div>
      </div>
    </div>
  );
}

function VoiceBar({ label, value }: { label: string; value: number }) {
  const [left, right] = label.split(' / ');
  return (
    <div>
      <div className="flex justify-between text-[10px] text-text-3 mb-1">
        <span>{left}</span>
        <span>{right}</span>
      </div>
      <div className="h-1 bg-border rounded-full relative">
        <div
          className="absolute top-1/2 -translate-y-1/2 -translate-x-1/2 w-2.5 h-2.5 bg-accent rounded-full ring-2 ring-bg-elev"
          style={{ left: `${value}%` }}
        />
      </div>
    </div>
  );
}

const CONFIDENCE_TINT: Record<
  AutoGeneratedBrandBible['confidence'],
  string
> = {
  high: 'bg-emerald-500/15 text-emerald-500',
  medium: 'bg-amber-500/15 text-amber-500',
  low: 'bg-danger/15 text-danger',
};

function GeneratedPreviewModal({
  generated,
  onClose,
  onApply,
}: {
  generated: AutoGeneratedBrandBible;
  onClose: () => void;
  onApply: () => void;
}) {
  const [applying, setApplying] = useState(false);

  const handleApply = async () => {
    setApplying(true);
    try {
      await onApply();
    } finally {
      setApplying(false);
    }
  };

  return (
    <div
      className="fixed inset-0 bg-black/60 z-[60] flex items-start justify-center p-4 overflow-auto backdrop-blur-sm"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <GlassCard
        elevated
        className="max-w-2xl w-full p-6 my-8"
      >
        <div className="flex items-start justify-between mb-4 gap-3">
          <div className="min-w-0">
            <div className="text-[10px] font-mono uppercase tracking-[0.15em] text-text-3 mb-1">
              Generated brand bible · review
            </div>
            <h3 className="font-display text-2xl font-light">
              Apply to project?
            </h3>
            <p className="text-xs text-text-2 mt-1">
              Existing fields you&apos;ve set are preserved. This only fills
              archetype, voice, pillars, audience, and adds quotes to your
              brand phrases.
            </p>
          </div>
          <span
            className={`text-[10px] font-mono uppercase tracking-[0.1em] px-2 py-1 rounded shrink-0 ${CONFIDENCE_TINT[generated.confidence]}`}
            title={generated.confidenceReasoning}
          >
            {generated.confidence} confidence
          </span>
        </div>

        <div className="space-y-5">
          <div className="p-4 bg-bg rounded-lg border border-border">
            <div className="text-[10px] font-mono uppercase tracking-[0.15em] text-text-3 mb-1">
              Archetype
            </div>
            <div className="text-xl font-display capitalize mb-1">
              {generated.archetype || '—'}
            </div>
            {generated.archetypeReasoning && (
              <p className="text-xs text-text-2">
                {generated.archetypeReasoning}
              </p>
            )}
          </div>

          <div>
            <div className="text-[10px] font-mono uppercase tracking-[0.15em] text-text-3 mb-3">
              Voice
            </div>
            <div className="space-y-3">
              <VoiceBar
                label="Casual / Formal"
                value={generated.voiceCasualFormal}
              />
              <VoiceBar
                label="Playful / Serious"
                value={generated.voicePlayfulSerious}
              />
              <VoiceBar
                label="Reserved / Bold"
                value={generated.voiceReservedBold}
              />
              <VoiceBar
                label="Traditional / Innovative"
                value={generated.voiceTraditionalInnovative}
              />
            </div>
          </div>

          {generated.pillars.length > 0 && (
            <div>
              <div className="text-[10px] font-mono uppercase tracking-[0.15em] text-text-3 mb-2">
                Pillars
              </div>
              <div className="flex flex-wrap gap-2 mb-2">
                {generated.pillars.map((p) => (
                  <span
                    key={p}
                    className="px-3 py-1 bg-accent-soft text-accent rounded-full text-xs"
                  >
                    {p}
                  </span>
                ))}
              </div>
              {generated.pillarsReasoning && (
                <p className="text-xs text-text-3">
                  {generated.pillarsReasoning}
                </p>
              )}
            </div>
          )}

          {(generated.audienceDescription ||
            generated.audienceDemographics) && (
            <div className="p-4 bg-bg rounded-lg border border-border">
              <div className="text-[10px] font-mono uppercase tracking-[0.15em] text-text-3 mb-1">
                Audience
              </div>
              {generated.audienceDescription && (
                <p className="text-sm">{generated.audienceDescription}</p>
              )}
              {generated.audienceDemographics && (
                <p className="text-xs text-text-3 mt-1">
                  {generated.audienceDemographics}
                </p>
              )}
            </div>
          )}

          {generated.quoteVault.length > 0 && (
            <div>
              <div className="text-[10px] font-mono uppercase tracking-[0.15em] text-text-3 mb-2">
                Voice samples (added to brand phrases)
              </div>
              <div className="space-y-2">
                {generated.quoteVault.map((q, i) => (
                  <div
                    key={i}
                    className="p-3 bg-bg rounded text-xs italic border-l-2 border-accent"
                  >
                    “{q}”
                  </div>
                ))}
              </div>
            </div>
          )}

          {generated.discrepancies.length > 0 && (
            <div className="p-4 bg-amber-500/10 border border-amber-500/30 rounded-lg">
              <div className="text-[10px] font-mono uppercase tracking-[0.15em] text-amber-500 mb-2">
                ⚠ Discrepancies detected
              </div>
              <div className="space-y-2">
                {generated.discrepancies.map((d, i) => (
                  <div key={i} className="text-xs">
                    <div className="font-medium capitalize">
                      {d.type.replace(/_/g, ' ')}
                    </div>
                    <div className="text-text-2">{d.description}</div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        <div className="flex flex-wrap items-center justify-between gap-2 mt-6 pt-4 border-t border-border">
          <Button variant="ghost" size="sm" onClick={onClose}>
            Discard
          </Button>
          <Button size="sm" onClick={handleApply} disabled={applying}>
            {applying ? 'Applying…' : 'Apply to project'}
          </Button>
        </div>
      </GlassCard>
    </div>
  );
}
