// PR Sprint 7.25 Phase 10 — landing brand-bible preview.
//
// Visual rendering of the AutoGeneratedBrandBible returned by
// /api/landing/preview-bible. Sits inside the demo section
// directly under the terminal form so a stranger sees their own
// brand reflected back BEFORE we ask them to sign up.
//
// Shape we render:
//   - Archetype chip + reasoning (italic Instrument Serif quote)
//   - 4 voice sliders (casual↔formal, playful↔serious,
//     reserved↔bold, traditional↔innovative) with the model's
//     position dot
//   - 3-5 brand pillars as chips
//   - Audience description block
//   - 2-3 quotes from the brand's site (quote vault sample)
//   - Confidence badge with reasoning tooltip
//   - Bottom: orange "Claim your spot" CTA aligned with the rest
//     of the landing's primary buttons. Routes to /signup?url=
//     <encoded> so the post-confirmation onboarding picks up where
//     the preview left off.
'use client';

import Link from 'next/link';
import type { AutoGeneratedBrandBible } from '@/lib/brand-bible/auto-generate';

interface Props {
  bible: AutoGeneratedBrandBible;
  brandName: string;
  url: string;
}

const VOICE_AXES: Array<{
  key: keyof AutoGeneratedBrandBible;
  left: string;
  right: string;
}> = [
  { key: 'voiceCasualFormal', left: 'Casual', right: 'Formal' },
  { key: 'voicePlayfulSerious', left: 'Playful', right: 'Serious' },
  { key: 'voiceReservedBold', left: 'Reserved', right: 'Bold' },
  { key: 'voiceTraditionalInnovative', left: 'Traditional', right: 'Innovative' },
];

function ConfidenceChip({
  level,
  reasoning,
}: {
  level: 'low' | 'medium' | 'high';
  reasoning: string;
}) {
  const tone =
    level === 'high'
      ? { bg: 'rgba(34,197,94,0.1)', border: 'rgba(34,197,94,0.32)', color: 'var(--d-green-2)' }
      : level === 'medium'
        ? { bg: 'rgba(96,165,250,0.1)', border: 'rgba(96,165,250,0.32)', color: 'var(--d-blue-2)' }
        : { bg: 'rgba(249,115,22,0.1)', border: 'rgba(249,115,22,0.32)', color: 'var(--d-orange-2)' };
  return (
    <span
      className="bible-preview-confidence"
      style={{
        background: tone.bg,
        borderColor: tone.border,
        color: tone.color,
      }}
      title={reasoning || `Confidence: ${level}`}
    >
      {level} confidence
    </span>
  );
}

export function BiblePreview({ bible, brandName, url }: Props) {
  // Cap quotes to 3 for the preview so the card breathes; the full
  // bible gets the entire vault once they sign up.
  const quotes = bible.quoteVault.slice(0, 3);
  const pillars = bible.pillars.slice(0, 5);
  const claimUrl = `/signup?url=${encodeURIComponent(url)}`;

  return (
    <div className="bible-preview-card platform-reveal-2">
      <header className="bible-preview-head">
        <div>
          <div className="bible-preview-eyebrow">
            brand bible · {brandName}
          </div>
          <h3 className="bible-preview-archetype">
            <span className="bible-preview-archetype-word">
              {bible.archetype}
            </span>
            <span className="bible-preview-archetype-sub">archetype</span>
          </h3>
          {bible.archetypeReasoning && (
            <p className="bible-preview-reasoning">
              &ldquo;{bible.archetypeReasoning}&rdquo;
            </p>
          )}
        </div>
        <ConfidenceChip
          level={bible.confidence}
          reasoning={bible.confidenceReasoning}
        />
      </header>

      {/* Voice axes — four sliders with the model's pick as the dot.
          Mirrors the Settings → Brand Bible voice block so a founder
          who signs up doesn't see a different scale than the preview. */}
      <section className="bible-preview-section">
        <div className="bible-preview-label">Voice fingerprint</div>
        <div className="bible-preview-voices">
          {VOICE_AXES.map((axis) => {
            const value = Number(bible[axis.key] ?? 50);
            return (
              <div key={axis.key} className="bible-voice-row">
                <span className="bible-voice-left">{axis.left}</span>
                <div className="bible-voice-track">
                  <span
                    className="bible-voice-dot"
                    style={{ left: `calc(${value}% - 8px)` }}
                  />
                </div>
                <span className="bible-voice-right">{axis.right}</span>
              </div>
            );
          })}
        </div>
      </section>

      {/* Pillars + audience side by side on desktop, stacked mobile. */}
      <div className="bible-preview-grid">
        {pillars.length > 0 && (
          <section className="bible-preview-section">
            <div className="bible-preview-label">Brand pillars</div>
            <div className="bible-preview-pillars">
              {pillars.map((p, i) => (
                <span key={i} className="bible-preview-pillar-chip">
                  {p}
                </span>
              ))}
            </div>
            {bible.pillarsReasoning && (
              <p className="bible-preview-tiny">{bible.pillarsReasoning}</p>
            )}
          </section>
        )}

        {(bible.audienceDescription || bible.audienceDemographics) && (
          <section className="bible-preview-section">
            <div className="bible-preview-label">Audience</div>
            {bible.audienceDescription && (
              <p className="bible-preview-body">
                {bible.audienceDescription}
              </p>
            )}
            {bible.audienceDemographics && (
              <p className="bible-preview-tiny">
                {bible.audienceDemographics}
              </p>
            )}
          </section>
        )}
      </div>

      {/* Quote vault sample — most evocative signal that the preview
          is grounded in their actual brand voice. */}
      {quotes.length > 0 && (
        <section className="bible-preview-section">
          <div className="bible-preview-label">
            Pulled from your site · {bible.quoteVault.length} quote
            {bible.quoteVault.length === 1 ? '' : 's'}
          </div>
          <ul className="bible-preview-quotes">
            {quotes.map((q, i) => (
              <li key={i} className="bible-preview-quote">
                &ldquo;{q}&rdquo;
              </li>
            ))}
          </ul>
        </section>
      )}

      <footer className="bible-preview-footer">
        <div className="bible-preview-cta-copy">
          <div className="bible-preview-cta-eyebrow">save this bible</div>
          <p>
            Claim your spot and Helm keeps reading — adds your social
            accounts, finds the rooms your audience hangs out in, and
            turns this bible into posts that sound like you.
          </p>
        </div>
        <Link
          href={claimUrl}
          className="landing-btn landing-btn-primary bible-preview-cta-btn"
        >
          Claim your spot
          <svg width="14" height="14" viewBox="0 0 16 16" fill="none" aria-hidden>
            <path
              d="M3 8h10M9 4l4 4-4 4"
              stroke="currentColor"
              strokeWidth="1.8"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        </Link>
      </footer>
    </div>
  );
}
