'use client';

// PR Sprint 7.25 Phase 10 — landing brand-bible preview.
//
// The "$ helm read <url>" demo on the landing now actually
// generates a brand bible inline, BEFORE asking the visitor to
// sign up. Flow:
//   1. Visitor types a URL → client validates (yourbrand.com works).
//   2. Submit → POST /api/landing/preview-bible. The endpoint
//      scrapes the public surface and runs the Opus brand-bible
//      builder. ~12-30s total.
//   3. While loading, we show the ShipsWheelLoader (the new design-
//      system "definite work" loader). No estimate countdown — the
//      response lands when it lands.
//   4. On success the <BiblePreview /> component renders the
//      archetype + voice fingerprint + pillars + audience +
//      quote vault. THAT card carries the "Claim your spot" CTA
//      that finally routes to /signup?url=<encoded>.
//   5. On error we surface the server's hint inline and let them
//      retry. Rate-limit hits include a "wait N minutes" message.
//
// Phase-8 behaviour (immediate /signup redirect) is gone — the
// demo now sells the product BEFORE asking for the email.
import { useRef, useState } from 'react';
import { ShipsWheelLoader } from '@/components/ui/loaders';
import { BiblePreview } from './bible-preview';
import type { AutoGeneratedBrandBible } from '@/lib/brand-bible/auto-generate';

function normaliseUrl(raw: string): string | null {
  const trimmed = raw.trim();
  if (!trimmed) return null;
  const withScheme = /^https?:\/\//i.test(trimmed)
    ? trimmed
    : `https://${trimmed}`;
  try {
    const u = new URL(withScheme);
    if (!u.hostname.includes('.')) return null;
    return u.toString();
  } catch {
    return null;
  }
}

interface BibleResponse {
  ok: boolean;
  bible?: AutoGeneratedBrandBible;
  brandName?: string;
  url?: string;
  error?: string;
  hint?: string;
}

type State =
  | { kind: 'idle' }
  | { kind: 'loading' }
  | { kind: 'error'; message: string }
  | {
      kind: 'ready';
      bible: AutoGeneratedBrandBible;
      brandName: string;
      url: string;
    };

export function DemoUrlForm() {
  const [value, setValue] = useState('');
  const [state, setState] = useState<State>({ kind: 'idle' });
  // Scroll target so we can ease the page down to the bible result
  // once it lands — without it, on a tall hero the founder might
  // miss that the preview appeared below the fold.
  const resultRef = useRef<HTMLDivElement | null>(null);

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (state.kind === 'loading') return;
    const normalised = normaliseUrl(value);
    if (!normalised) {
      setState({
        kind: 'error',
        message: 'Enter a real URL (e.g. yourbrand.com)',
      });
      return;
    }
    setState({ kind: 'loading' });
    try {
      const res = await fetch('/api/landing/preview-bible', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: normalised }),
      });
      const data = (await res.json().catch(() => ({}))) as BibleResponse;
      if (!res.ok || !data.ok || !data.bible) {
        const msg =
          (data.error ?? 'Could not read that brand') +
          (data.hint ? ` — ${data.hint}` : '');
        setState({ kind: 'error', message: msg });
        return;
      }
      setState({
        kind: 'ready',
        bible: data.bible,
        brandName: data.brandName ?? 'Your brand',
        url: data.url ?? normalised,
      });
      // Let the new DOM render, then scroll the preview into view.
      // Two frames are enough for the platform-reveal-2 keyframe to
      // mount + start; the smooth scroll handles the rest.
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          resultRef.current?.scrollIntoView({
            behavior: 'smooth',
            block: 'start',
          });
        });
      });
    } catch (err) {
      setState({
        kind: 'error',
        message:
          err instanceof Error
            ? err.message
            : 'Network error — please try again',
      });
    }
  };

  const isLoading = state.kind === 'loading';
  const isReady = state.kind === 'ready';

  return (
    <>
      <form className="landing-demo-shell" onSubmit={submit} noValidate>
        <span className="prompt">$</span>
        <span className="cmd-prefix">helm read</span>
        <input
          className="cmd-input"
          type="text"
          inputMode="url"
          autoComplete="url"
          spellCheck={false}
          placeholder="https://your-brand.com"
          aria-label="Your brand URL"
          value={value}
          onChange={(e) => {
            setValue(e.target.value);
            if (state.kind === 'error') setState({ kind: 'idle' });
          }}
          disabled={isLoading}
        />
        {isLoading ? (
          // PR Sprint 7.25 Phase 10 — the same Ship's Wheel that
          // shows on slide / single-image generation. Same visual
          // language, same "Helm is doing definite work" signal.
          <ShipsWheelLoader
            size={32}
            vertical={false}
            label="Reading brand"
          />
        ) : (
          <button
            type="submit"
            className="send"
            disabled={value.trim().length === 0}
          >
            {isReady ? 'Re-read' : 'Read brand'}
            <svg width="14" height="14" viewBox="0 0 16 16" fill="none" aria-hidden>
              <path
                d="M3 8h10M9 4l4 4-4 4"
                stroke="currentColor"
                strokeWidth="1.8"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </button>
        )}
        {state.kind === 'error' && (
          <span
            role="alert"
            className="cmd-error"
            style={{ color: 'var(--d-red-2)' }}
          >
            {state.message}
          </span>
        )}
      </form>

      {/* Bible result — sits directly under the terminal so the
          visitor sees the WOW moment without scrolling. The
          BiblePreview card carries its own CTA that routes to
          /signup?url=<encoded>. */}
      <div
        ref={resultRef}
        className="landing-demo-result"
        aria-live="polite"
        aria-busy={isLoading}
      >
        {isLoading && (
          <div className="landing-demo-loading" aria-hidden>
            <ShipsWheelLoader
              size={64}
              label="Reading your brand"
              subLabel="archetype · voice · pillars · audience"
            />
          </div>
        )}
        {isReady && (
          <BiblePreview
            bible={state.bible}
            brandName={state.brandName}
            url={state.url}
          />
        )}
      </div>
    </>
  );
}
