-- PR Sprint 7.19 Round 3a — daily snapshot table for the
-- analytics insight engine.
--
-- One row per (project, day, metric_key). The cron job at
-- /api/cron/snapshot-metrics runs daily at 03:00 UTC and writes
-- a row per (project, metric) tuple. The insight engine
-- (Round 3b) reads from this table to compute anomalies and
-- generate hypotheses.
--
-- Idempotent: CREATE TABLE IF NOT EXISTS + UNIQUE constraint
-- on (project_id, snapshot_date, metric_key) lets the cron
-- re-run safely.

CREATE TABLE IF NOT EXISTS metric_daily_snapshots (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Soft ref. We DON'T cascade-delete on project removal —
  -- historical data outlives the project so the founder can
  -- still see "we tried X and it failed" after archiving.
  project_id       UUID NOT NULL,
  -- ISO date (YYYY-MM-DD) of the day this snapshot represents.
  -- Stored as a real DATE so range queries are index-friendly.
  snapshot_date    DATE NOT NULL,
  -- Stable identifier for the metric. Examples:
  --   'posts.drafts.total'
  --   'posts.drafts.created_today'
  --   'posts.scheduled.total'
  --   'posts.published.total'
  --   'posts.published.today'
  --   'chat.conversations.active'
  --   'chat.messages.today'
  --   'integrations.count'
  --   'research.findings.total'
  --   'research.findings.today'
  --   'compass.decisions.total'
  --   'voice_engine.audit_events.today'
  -- Round 3b's anomaly detector keys off this column to
  -- discover trends; Round 3c's digest groups by it.
  metric_key       TEXT NOT NULL,
  -- Numeric value of the metric for the day. NUMERIC so we can
  -- store ratios (engagement rate) or counts (post count)
  -- without two columns.
  value            NUMERIC NOT NULL,
  -- Optional dimensions for slicing (platform, content_type,
  -- etc). Kept as JSONB so we don't need a column per
  -- dimension. Example: { "platform": "linkedin" }.
  -- The (project, date, metric, dimensions_hash) tuple is what
  -- the unique index enforces; nullable for un-sliced metrics.
  dimensions       JSONB,
  -- Stable hash of dimensions for the unique index. NULL for
  -- un-sliced metrics. Generated by the cron via
  -- md5(jsonb_stripped_dimensions). Index handles NULL via
  -- COALESCE.
  dimensions_hash  TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Unique index so the cron can UPSERT idempotently. The
-- COALESCE makes NULL dimensions hash to a sentinel string so
-- (project, day, metric, NULL) is unique exactly once.
CREATE UNIQUE INDEX IF NOT EXISTS metric_daily_snapshots_uniq_idx
  ON metric_daily_snapshots (
    project_id,
    snapshot_date,
    metric_key,
    COALESCE(dimensions_hash, '')
  );

-- Hot-path lookups: "give me the last 30 days of metric_key X
-- for project Y" — the anomaly detector's workhorse query.
CREATE INDEX IF NOT EXISTS metric_daily_snapshots_lookup_idx
  ON metric_daily_snapshots (project_id, metric_key, snapshot_date DESC);

-- Global cross-project queries for the admin overview ("how
-- many posts were published yesterday across all projects?").
CREATE INDEX IF NOT EXISTS metric_daily_snapshots_global_idx
  ON metric_daily_snapshots (snapshot_date DESC, metric_key);
