// PR Sprint 7.25 Phase 11 — HeyGen queue worker.
//
// GET /api/cron/heygen-worker  (auth: Bearer CRON_SECRET)
//
// The /api/ai/generate-structured route inserts a heygen_jobs row
// with status='queued' for every UGC / Reel draft. Pre-this-PR
// nothing actually called HeyGen unless the founder had the
// generator card mounted in the browser (the Phase-9 client auto-
// fire). Drafts created and then left alone (or generated by a
// future automation) never got rendered.
//
// This cron drains the queue every minute on Vercel Pro:
//   1. Pull the oldest N queued jobs PLUS failed rows that are
//      eligible for retry (attemptCount < MAX_HEYGEN_ATTEMPTS AND
//      errorKind suggests a transient upstream error, not a
//      configuration error).
//   2. For each, verify the project's HeyGen avatar is still
//      configured. Skip silently if not — the next tick will
//      re-try automatically once the founder picks an avatar in
//      Settings (the row stays `status='queued'`).
//   3. Fire the shared `fireHeygenForJob` helper. Each call hits
//      HeyGen, captures the upstream video_id, increments
//      attemptCount, and flips the row to status='processing'
//      (or back to 'failed' if it errored again). HeyGen's own
//      webhook (/api/heygen/webhook) lands the final 'completed'
//      transition asynchronously.
//
// Batch sizing: 5 jobs per tick. HeyGen accepts the generate call
// in <2s typically; we cap at 5 to stay well under Vercel's 60s
// function ceiling even when an avatar lookup or DB round-trip is
// slow.
//
// Retry policy (PR Sprint 7.25 Phase 11.5):
//   - Transient errors (errorKind='upstream_error') → eligible
//     for retry. These are HeyGen 5xx, network timeouts, etc.
//   - Configuration errors (errorKind='voice_config') → NEVER
//     auto-retried. Founder must fix the voice in Settings.
//   - Hard retry cap at MAX_HEYGEN_ATTEMPTS (3). Past that we
//     leave the row failed and surface the "🎬 Retry video"
//     button in the Library detail modal for manual override.
//
// Idempotency: fireHeygenForJob updates the row to 'processing'
// (or 'failed') before returning, so a concurrent tick that
// happened to pick the same row would see status !== 'queued' on
// its second pass and skip. Belt-and-suspenders: we also re-check
// status + attemptCount inside the loop after the DB read.
//
// Auth: same CRON_SECRET bearer pattern as every other cron in
// this repo. Refuses if the env var is unset.

import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { heygenJobs, projects } from '@/lib/db/schema';
import { eq, and, or, asc, sql } from 'drizzle-orm';
import {
  isHeygenEnvConfigured,
  isHeygenReadyForProject,
} from '@/lib/heygen/gate';
import { fireHeygenForJob } from '@/lib/heygen/fire';

export const dynamic = 'force-dynamic';
// HeyGen generate calls are typically 1-2s each. Five sequential
// calls + DB roundtrips fits comfortably under 60s.
export const maxDuration = 60;

const BATCH_LIMIT = 5;
// Hard retry cap. Past this we leave the row failed and surface
// the manual "🎬 Retry video" button in the Library modal.
// Three tries × ~$0.10 per HeyGen call = $0.30 worst-case spend
// per stuck video, which beats both silent failure and unbounded
// retry loops.
const MAX_HEYGEN_ATTEMPTS = 3;

interface WorkerSummary {
  considered: number;
  processed: number;
  succeeded: number;
  failed: number;
  skippedNotConfigured: number;
  retriedFailedRows: number;
  errors: Array<{ jobId: string; reason: string }>;
}

export async function GET(request: Request) {
  // Auth gate. CRON_SECRET MUST be set; otherwise nothing publishes.
  const expected = process.env.CRON_SECRET;
  if (!expected) {
    return NextResponse.json(
      { error: 'CRON_SECRET not configured on server' },
      { status: 503 },
    );
  }
  const auth = request.headers.get('authorization');
  if (auth !== `Bearer ${expected}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  // Env gate. If HeyGen isn't enabled deployment-wide, the cron
  // is a no-op — log + return early so the founder doesn't burn
  // a tick worth of DB queries every minute when the integration
  // is dark.
  if (!isHeygenEnvConfigured()) {
    return NextResponse.json({
      success: true,
      skipped: true,
      reason: 'HEYGEN_ENABLED is off; cron is a no-op until env is configured',
    });
  }

  // Pull queued rows AND retry-eligible failed rows. Retry-eligible
  // = errorKind='upstream_error' (transient HeyGen / network) AND
  // attemptCount < MAX_HEYGEN_ATTEMPTS. We intentionally exclude
  // errorKind='voice_config' from the retry sweep — those need a
  // founder action in Settings, no amount of retrying changes the
  // upstream's mind.
  const candidates = await db
    .select({ job: heygenJobs, project: projects })
    .from(heygenJobs)
    .innerJoin(projects, eq(projects.id, heygenJobs.projectId))
    .where(
      or(
        eq(heygenJobs.status, 'queued'),
        and(
          eq(heygenJobs.status, 'failed'),
          eq(heygenJobs.errorKind, 'upstream_error'),
          sql`${heygenJobs.attemptCount} < ${MAX_HEYGEN_ATTEMPTS}`,
        ),
      ),
    )
    .orderBy(asc(heygenJobs.requestedAt))
    .limit(BATCH_LIMIT);

  const summary: WorkerSummary = {
    considered: candidates.length,
    processed: 0,
    succeeded: 0,
    failed: 0,
    skippedNotConfigured: 0,
    retriedFailedRows: 0,
    errors: [],
  };

  for (const { job, project } of candidates) {
    // Belt-and-suspenders: a parallel tick may have already
    // claimed this row by flipping it to 'processing'. Re-read
    // status + attemptCount before firing.
    const [fresh] = await db
      .select({
        status: heygenJobs.status,
        errorKind: heygenJobs.errorKind,
        attemptCount: heygenJobs.attemptCount,
      })
      .from(heygenJobs)
      .where(eq(heygenJobs.id, job.id))
      .limit(1);
    if (!fresh) continue;
    const isQueued = fresh.status === 'queued';
    const isRetryable =
      fresh.status === 'failed' &&
      fresh.errorKind === 'upstream_error' &&
      (fresh.attemptCount ?? 0) < MAX_HEYGEN_ATTEMPTS;
    if (!isQueued && !isRetryable) continue;
    if (!isQueued && isRetryable) {
      summary.retriedFailedRows += 1;
      // Flip back to queued so fireHeygenForJob's idempotency
      // check (status === 'queued' || 'failed') sees a clean
      // starting state. attempt_count keeps climbing — fire bumps
      // it on every miss.
      await db
        .update(heygenJobs)
        .set({ status: 'queued', errorMessage: null, errorKind: null })
        .where(eq(heygenJobs.id, job.id));
    }

    // Project-level gate. Same rule as the user-driven endpoint:
    // skip projects that haven't configured an avatar yet. We do
    // NOT flip the row to 'failed' here — leaving it as 'queued'
    // means the next tick will retry automatically once the
    // founder picks an avatar in Settings.
    if (!isHeygenReadyForProject(project)) {
      summary.skippedNotConfigured += 1;
      continue;
    }

    summary.processed += 1;
    try {
      const result = await fireHeygenForJob(job, project);
      if (result.ok) {
        summary.succeeded += 1;
      } else {
        summary.failed += 1;
        summary.errors.push({
          jobId: job.id,
          reason: `${result.errorKind}: ${result.error.slice(0, 200)}`,
        });
      }
    } catch (e) {
      // fireHeygenForJob already handles HeyGen-side failures and
      // marks the row 'failed'. This catch is for unexpected
      // throws (DB connection drops, etc.).
      summary.failed += 1;
      const msg = e instanceof Error ? e.message : String(e);
      summary.errors.push({ jobId: job.id, reason: `worker: ${msg}` });
      await db
        .update(heygenJobs)
        .set({
          status: 'failed',
          errorMessage: msg.slice(0, 500),
          errorKind: 'upstream_error',
          completedAt: new Date(),
        })
        .where(eq(heygenJobs.id, job.id))
        .catch(() => {
          /* non-fatal */
        });
    }
  }

  return NextResponse.json({
    success: true,
    ...summary,
  });
}
